### ISSUE TITLE
[REQ] PHP 8.3 Website Support

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#10]
Support for PHHP 8.3, would it be possible?

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/32937653/1e742de6-be59-4664-8bf3-6a246002396f)

I tried versions 7.3> and none of them worked?

**Comment by Nereziel** [comment]
I have 8.2.3 and no problems.

**Comment by crashzk** [comment]
My mistake, sorry.

**Comment by Truyn** [comment]
What was the problem? I have the same error php 8.2
