### ISSUE TITLE
add this to translations

### ISSUE THREAD

**Issue by Nereziel** [Nereziel/cs2-WeaponPaints#103]
[WeaponPaints]  Refreshing weapon paints
[WeaponPaints]  You can't refresh weapon paints right now

**Comment by daffyyyy** [comment]
```
	"wp_command_cooldown": "{lightred}You can't refresh weapon paints right now",
	"wp_command_refresh_done": "{lime}Refreshing weapon paints",

```

Currently here?

**Comment by Nereziel** [comment]
Thanks, i just created issue, bcs someone reported, it was missing.
