### ISSUE TITLE
BUG Names??

### ISSUE THREAD

**Issue by asdfxD** [Nereziel/cs2-WeaponPaints#106]
i use karambit fade knife and sometimes it says on right just ★ Karambit and sometimes ★ Karambit | Fade

it's bugged i guess.

edit: same with other skins, !wp does not fix it.
![20231223123655_1](https://github.com/Nereziel/cs2-WeaponPaints/assets/24253340/82b87cce-08e8-4df3-bafa-2ea0e9556153)

**Comment by crashzk** [comment]
It is already a known bug, but no fix yet. We need to wait for updates from CSSharp.

**Comment by Nereziel** [comment]
Not a priority, visually you have selected skin.
