### ISSUE TITLE
Can't getting skins from database

### ISSUE THREAD

**Issue by etkosko** [Nereziel/cs2-WeaponPaints#110]
I setup all things, configs GlobalShare is "false" because I setup my own mysql and it works I build my website you can change the skins knifes and it saving mySQL no problem but in game I cant reach the skins from database it wont come (I guess this cause by database). I filled WeaponPaints.json's mySQL informations and when I buy something in game on buy menu the gun coming my hand twice like a switching weapon. I tried with my friend in chat comamnd !knife it'll give knife to my friend. (he dont have knife) but I cant get with !knife command on chat (I have my own knife).

**Comment by audiomaster99** [comment]
> **Skins are not changing:**
Set `FollowCSGOGuidelines` to `false` in cssharp’s core.jcon config

For the gun switch disable skinvisibilityfix in config

**Comment by etkosko** [comment]
Thanks for the infos gudilines already "false "and the setting the skinvisibilty disable fixed switch and having my own knife maked me sad but i hope it will fix. problem its because my friend tell me he created tables with own hand. I checked Utility.cs and saw it already creating table. so I just DROP TABLE and letted to code creating again.
