### ISSUE TITLE
[enhancement request] better logic to use plugin without website

### ISSUE THREAD

**Issue by criskkky** [Nereziel/cs2-WeaponPaints#113]
Hi guys,
to improve the way how players change their skins without website you could add this commands:

**SEED:**
`!seed {value}`
> example: !seed 41

**WEAR**
`!wear {value}`
>example: !wear 0

> Factory New - 0 – 0.07
> Minimal Wear - 0.07 – 0.15
> Field-Tested - 0.15 – 0.37
> Well-Worn - 0.37 – 0.44
> Battle-Scarred - 0.44 – 1

**FAST WAY TO USE !SKINS**
1. Players uses: `!skins {weapon_name}`
2. Server send to client the list of skins available for that {weapon_name}

>example: !skins butterfly

**Comment by criskkky** [comment]
Sorry, I was reading Spanish repositories and ended up writing the issue title in Spanish XD

**Comment by L1teD** [comment]
I think better name this commands as pattern and float, because i think more people use these words (or not idk, mb I'm wrong)

**Comment by criskkky** [comment]
> @L1teD:
> I think better name this commands as pattern and float, because i think more people use these words (or not idk, mb I'm wrong)

Or anyone defines it in the config file :D
