### ISSUE TITLE
Knives are not provided

### ISSUE THREAD

**Issue by Truyn** [Nereziel/cs2-WeaponPaints#116]
The latest version of the plugin, awp lego server, at first there was a bug that the knives disappeared after winning, after updating the plugin they disappeared altogether.

**Comment by Truyn** [comment]
I turned off the knives in the configuration and the weapon skins stopped working.

**Comment by crashzk** [comment]
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/32937653/707df809-ff64-468a-a407-0a7c623d5bbc)

Duplicate #119

**Comment by Nereziel** [comment]
is this actual?
