### ISSUE TITLE
Skins BUG

### ISSUE THREAD

**Issue by criskkky** [Nereziel/cs2-WeaponPaints#117]
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/36176343/5f0d1dd6-292f-431e-90fb-dd22602e7dc6)

Fix pls :(, happens with all ak47 skins

**Comment by criskkky** [comment]
Update: happens with usps too lol, is something that I should edit in cfg or is code problem?

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/36176343/ee043504-2f80-422a-ac65-a87acfe791f1)

**Comment by criskkky** [comment]
I'm using build 168 btw

**Comment by mihaigsm2003** [comment]
skins bugs on latest vers

**Comment by criskkky** [comment]
oh okey

**Comment by criskkky** [comment]
Fixed
