### ISSUE TITLE
why this is so f hard !!

### ISSUE THREAD

**Issue by Kamii193** [Nereziel/cs2-WeaponPaints#118]
u said : 
Setup addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json set GlobalShare to true for global, or include database credentials

bruh im i stu pid or what , when i go to this folder i find WeaponPaints.deps.json i rename it to WeaponPaints.json and clicked on it , I CANT FIND GlobalShare  TO SET TO TRUE BROO

**Comment by evenbreak** [comment]
u should not rename weaponpaints.deps.json to weaponpaints.json

leave weaponpaints.deps.json as it is, DO NOT change it, never.

csgo/addons/counterstrikesharp/configs/plugins/weaponpaints/weaponspaint.json

in the folder u will only see weaponpaints.json  and thats all

**Comment by Kamii193** [comment]
@evenbreak for me there is no weaponpaints.json only weaponpaints.deps.json 
should i run the server then weaponpaints.json will apper latter ,because i repeat i dont have weaponpaints.json

**Comment by Kamii193** [comment]
@evenbreak bro thank u so much i was so f blind ,it was my bad i didnt see config !!

**Comment by criskkky** [comment]
@Kamii193 if you don't know at 100% how to make a cs2 server you should pay to someone that makes it for you

**Comment by Kamii193** [comment]
> @Kamii193 if you don't know at 100% how to make a cs2 server you should pay to someone that makes it for you

Im slow learner but i learned a lot in the past week 
I made !ws works now but the skins are applying incorrectly in most of them 
And my server name doesn't show up in the website of skins even tho o setup database with myskl

**Comment by Kamii193** [comment]
@criskkky 
Im slow learner but i learned a lot in the past week 
I made !ws works now but the skins are applying incorrectly in most of them 
And my server name doesn't show up in the website of skins even tho o setup database with myskl

**Comment by Nereziel** [comment]
is this issue still actual?
