### ISSUE TITLE
Skins/Knife bug

### ISSUE THREAD

**Issue by evenbreak** [Nereziel/cs2-WeaponPaints#119]
I made the plugin work but once i choose the knife using !knife 

it works good for like one round but then i dont have knife anymore(literally only pistol and primary weapon) i cant pull my knife out

im using it on cs2 retake (https://github.com/B3none) so idk if the problem is with retake or the weaponpaints itself

**Comment by gabrielsdelima75** [comment]
**same problem**

metamod 1280
cssharp v153

weapon_paints Build 168

**Comment by evenbreak** [comment]
> **same problem**
> 
> metamod 1280 cssharp v153
> 
> weapon_paints Build 168

it seems like the problem lies on weaponpaint plugin rather than retake but idk

we gotta wait, i will check and try using it in a scrim server and see if the error appears, if yes, then we know the problem

**Comment by gabrielsdelima75** [comment]
> > **mesmo problema**
> > metamod 1280 cssharp v153
> > weapon_paints Compilação 168
> 
> Parece que o problema está no plugin weaponpaint em vez de retomar, mas idk
> 
> Temos que esperar, vou verificar e tentar usá-lo em um servidor scrim e ver se o erro aparece, se sim, então sabemos o problema

I created a multimode server (based on the repository: kus/cs2-modded-server), tested it in retakes, scrim, deathmatch modes... unfortunately same problem.

**Comment by evenbreak** [comment]
> > > **mesmo problema**
> > > metamod 1280 cssharp v153
> > > weapon_paints Compilação 168
> > 
> > 
> > Parece que o problema está no plugin weaponpaint em vez de retomar, mas idk
> > Temos que esperar, vou verificar e tentar usá-lo em um servidor scrim e ver se o erro aparece, se sim, então sabemos o problema
> 
> I created a multimode server (based on the repository: kus/cs2-modded-server), tested it in retakes, scrim, deathmatch modes... unfortunately same problem.

i wont even bother making one then, its the plugin skin itself that has this problem sadly

**Comment by crashzk** [comment]
From what I understand, the knife itself is being removed, right?

If so, have you tried?

> Knives are disappearing: Set in config GiveKnifeAfterRemove to true
> 

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/32937653/41e3bec1-5be0-4908-be6e-58a75bbf9666)

**Comment by evenbreak** [comment]
> From what I understand, the knife itself is being removed, right?
> 
> If so, have you tried?
> 
> > Knives are disappearing: Set in config GiveKnifeAfterRemove to true
> 
> ![image](https://private-user-images.githubusercontent.com/32937653/298969490-41e3bec1-5be0-4908-be6e-58a75bbf9666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDM1OTUsIm5iZiI6MTcwNjA0MzI5NSwicGF0aCI6Ii8zMjkzNzY1My8yOTg5Njk0OTAtNDFlM2JlYzEtNWJlMC00OTA4LWJlNmUtNThhNzViYmY5NjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIwNTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwN2Q3OWJmZTU1ODk0ZGU3ZmRhOTc5ZjFhZTM1MGRhYjJlZmM1N2M5NjE3YmMwMGEwMjM4MjZkNjhhZDIyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RCNZr66osxTYTZAvBMyaN8eIPp_rM85IR7_kYsyFaDI)
> 
> **[EDIT]** For me it apparently solved the problem.

thanks, i managed to make it work, but now what does not work is skin, no matter what, the skin doesnt show up in the server, even after !kill and !wp

idk what to do, followguide is false tho

**Comment by crashzk** [comment]
We need error logs now, so we know what it could be... Either a configuration error on your part or a bug in the plugin.

My servers are even running the plugin without errors.

**Comment by evenbreak** [comment]
> We need error logs now, so we know what it could be... Either a configuration error on your part or a bug in the plugin.
> 
> My servers are even running the plugin without errors.

i managed to make it work but every round i have to put the knife back, otherwise it goes back to default knife
also, whenever i have Globalshare "true" this issue happens

![2024-01-23_04-10-20](https://github.com/Nereziel/cs2-WeaponPaints/assets/149022728/b3ce0b05-cd52-4cb5-9e9d-caa9293bfa8e)

**Comment by gabrielsdelima75** [comment]
This topic was opened to report the skins bug issue. The problem with the knife disappearing was resolved by setting "GiveKnifeAfterRemove" to "true". However, the bug issue with Ak skins and other weapons is still pending...

**Comment by crashzk** [comment]
In fact, the issue was opened for the knife problem. Skins, you commented later, instead of opening another issue, which would have been correct.

That said, I tested the plugin here, the skins I choose are being saved normally, I enter and leave the map and the skin is there, a new round starts and the skin is there.

BUGS I found were:
- Even when using skins as new from the factory, they are still worn out, to test just put the **Desert Eagle | Blaze new from the factory** it is still worn out.
- Marioa of the skins when we select the weapon has a bug, it doesn't apply correctly. To test, just pick up the AK-47 | Asiimov, M4A1-S | Printstream, Glock-18 | Water Elemental all these skins are buggy, they don't apply correctly.

Where are you running the server? Linux/Windows? Rented server or dedicated machine?

**Comment by evenbreak** [comment]
> In fact, the issue was opened for the knife problem. Skins, you commented later, instead of opening another issue, which would have been correct.
> 
> That said, I tested the plugin here, the skins I choose are being saved normally, I enter and leave the map and the skin is there, a new round starts and the skin is there.
> 
> BUGS I found were:
> 
> * Even when using skins as new from the factory, they are still worn out, to test just put the **Desert Eagle | Blaze new from the factory** it is still worn out.
> * Marioa of the skins when we select the weapon has a bug, it doesn't apply correctly. To test, just pick up the **AK-47 | Asiimov, M4A1-S | Printstream & Glock-18 | Water Elemental** all these skins are buggy, they don't apply correctly.
> 
> Where are you running the server? Linux/Windows? Host server or dedicated server?

it was my mistake, my bad, im using linux as well

whenever i use globalshare true, the issue above happens(black bar and server crash)

**Comment by Nereziel** [comment]
so issue is in globalshare?
