### ISSUE TITLE
[REQ] Support StatTrak & NameTag

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#12]
Add support for StatTrak & NameTag to skins.

Apparently it is already in the project, but it would be interesting to change this option on the website.

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/32937653/a30fd094-c8c0-4372-8ae1-eaa92f95a2fa)

**Comment by NotVirusExeYT** [comment]
Where did u find this file?

**Comment by originalaidn** [comment]
added with 2.7a, soon will be adding commands for stattrak & nametag
