### ISSUE TITLE
Skins disappearing faster few rounds

### ISSUE THREAD

**Issue by evenbreak** [Nereziel/cs2-WeaponPaints#120]
fast forward, this issue happens quite often, the skins from knife and weapons dissappearing for few rounds and then back to normal, even if u use !wp it wont work

also weapon lags sometimes due to skin trying to refresh

idk why this happens tho

**Comment by crashzk** [comment]
Today I saw this bug too. In my case the knife skin is removed and returns to the CS2 default.

Some players using the `!wp` command are able to put it back, but others still have a bug.

This happens for a few rounds then the skins come back.

No error log is being generated.

**Note: I'm using my own MySQL database, the database itself has no errors.**

**MetaMod Version:** 2.0.0-dev+1280
**CSSharp Version:**  0.1.0 - API Version: 154 
**Plugin Version:** WeaponPaints 1.4a

**Comment by evenbreak** [comment]
> Today I saw this bug too. In my case the knife skin is removed and returns to the CS2 default.
> 
> Some players using the `!wp` command are able to put it back, but others still have a bug.
> 
> This happens for a few rounds then the skins come back.
> 
> No error log is being generated.
> 
> **Note: I'm using my own MySQL database, the database itself has no errors.**
> 
> **MetaMod Version:** 2.0.0-dev+1280 **CSSharp Version:** 0.1.0 - API Version: 154 **Plugin Version:** WeaponPaints 1.4a

Same here, the database is working fine, im hosting my own website tho as well

MetaMod V 2.0 dev 1280
CSS v154
Plugin Weapon 166

**Comment by criskkky** [comment]
Same here

**Comment by evenbreak** [comment]
> Same here
seems like to be db problem, but idk, need to confirm or wait for update

**Comment by asdfxD** [comment]
any fix? few respawns in dm, karambit is vanilla instead of fade.

**Comment by Nereziel** [comment]
Is this still actual?
