### ISSUE TITLE
How to make this plugin save the skins for players ? 

### ISSUE THREAD

**Issue by mayersgamer** [Nereziel/cs2-WeaponPaints#126]
- im setting the plugin to globalshare true 
- if i set globalshare false and put the database the plugin stop working 
- do i need to install the website for it to work and save skins for every player ?

**Comment by mihaigsm2003** [comment]
need install website

**Comment by Nereziel** [comment]
You need to provide correct database credentials in config, globalshare = false.
Website is not needed, but then you must rely on !skins command.

**Comment by mayersgamer** [comment]
ok it was the msql faulty , changed another one and it worked.
