### ISSUE TITLE
cant compile plugin

### ISSUE THREAD

**Issue by khanhuchiha** [Nereziel/cs2-WeaponPaints#13]
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/87079855/037ffb9c-5f1d-4f89-9938-14e28069cee7)

**Comment by crashzk** [comment]
Same error here with the latest version of the `main` branch

**Comment by khanhuchiha** [comment]
> Same error here with the latest version of the `main` branch

and the old version crashed with the new cssharp update

**Comment by khanhuchiha** [comment]
ya i found the problem is due to the typo error, bro got the double private at line 63 in the file
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/87079855/0ab1e869-c75c-4bc2-898d-4d535b61360e)

**Comment by Nereziel** [comment]
typo fixed
