### ISSUE TITLE
will this plugin work with metamod 1282 and css v162?

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#132]
Hello there ,

I want to install this but I'm not sure if it works with the new metamod and css . Has anyone tested to see if it works without crashing?

**Comment by rabi07** [comment]
Try and let us know.
I think it should work

**Comment by lostsoul6** [comment]
> its working

I tested . it crashes when refreshing weapon paints for me : 

https://github.com/Nereziel/cs2-WeaponPaints/issues/133

**Comment by daffyyyy** [comment]
#136
