### ISSUE TITLE
server crash when using !wp

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#133]
Hello There ,

I'm using metamod 1282 and css v162 on a Linux server and game server crashes when using !wp with no logs . I have edited refresh command to !refresh .

Here is the last log :

```
[All Chat][Mr. Reese (932662327)]: !refresh
L 02/07/2024 - 20:22:23: "Mr. Reese<1><[U:1:932662327]><TERRORIST>" say "!refresh"

Script done on 2024-02-07 20:22:24+03:30 [COMMAND_EXIT_CODE="139"]
```
it just crashes without error .

**Comment by mayersgamer** [comment]
yes it does

**Comment by criskkky** [comment]
Also crashing at

```
"crisky<0><[U:1:10876629]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 87.84 
./game/cs2.sh: line 118:    43 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

**Comment by lostsoul6** [comment]
New version hasn't fixed crashing issues . still crashes immediately after using !wp or in my case !refresh command . No errors in console .

metamod : 1282
css : v163
Linux

```
L 02/08/2024 - 14:12:28: World triggered "Round_Start"
[All Chat][Mr. Reese (932662327)]: !refresh
L 02/08/2024 - 14:12:39: "Mr. Reese<0><[U:1:932662327]><TERRORIST>" say "!refresh"

Script done on 2024-02-08 14:12:40+03:30 [COMMAND_EXIT_CODE="139"]
```

**Comment by daffyyyy** [comment]
#136

**Comment by lostsoul6** [comment]
@daffyyyy I updated gamedata.json to this file : https://github.com/roflmuffin/CounterStrikeSharp/files/14216124/gamedata.json
still server crashes instantly after refreshing weapon paints . can you please send me your gamedata.json ?
I'm using latest metamod and css on linux .

```
['Mr. Reese' tick 906 depth=1 (149) ping=2ms] CQ catchup: removed 5, max: 10
L 02/09/2024 - 14:06:35: World triggered "Round_Start"
[All Chat][Mr. Reese (932662327)]: !refresh
L 02/09/2024 - 14:06:41: "Mr. Reese<0><[U:1:932662327]><TERRORIST>" say "!refresh"

Script done on 2024-02-09 14:06:41+03:30 [COMMAND_EXIT_CODE="139"]
```

**Comment by StiliyanKushev** [comment]
Same issue. After `!knife` and any selection the server seg faults after a few seconds.
