### ISSUE TITLE
Crashing again (CS2 Update 2/8/2024)

### ISSUE THREAD

**Issue by criskkky** [Nereziel/cs2-WeaponPaints#137]
At JoinTeam (again), no error logs,
I'm using CSS-Linux v163, Metamod:Source version 2.0.0-dev+1282 & Latest WeaponPaints (v178).

**Comment by Miku-nya** [comment]
After update: there is a crash when choosing a new kukri knife
metamod 1282, css v163, weapon paints v178

**Comment by lostsoul6** [comment]
@criskkky do you have my issue as well ? server crashes instantly after refreshing weapon paints . this is the gamedata.json I'm using : https://github.com/roflmuffin/CounterStrikeSharp/pull/315#issuecomment-1935172398

**Comment by criskkky** [comment]
hi everyone, just update gamedata.json, i'll close 'cos it works.
