### ISSUE TITLE
reporting multiple issues with latest release

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#143]
Hi there ,

I noticed the following 4 issues with latest version :

1- when I join the server , the skins load properly . When I type !refresh (!wp) , all skins disappear from weapons . I recorded a video (sorry for audio quality - forgot to turn mic off) : 

https://github.com/Nereziel/cs2-WeaponPaints/assets/127633547/f6cbbe3c-1335-41d1-81db-ce37cdbc54d5

2- when I change my knife , all skins disappear and typing !refresh wouldn't fix it as well . I recorded a video : 

https://github.com/Nereziel/cs2-WeaponPaints/assets/127633547/efdf94ff-418b-41fa-91df-be6a7681e341

3- this one is a weird issue . I was playing as CT and picked up an AK at the end of the round . Next round at the spawn , I typed !refresh and the AK disappeared ! It took the gun away completely .

4- When I restart the server and join right after restart , obviously warm up is played . warm up is 1 and half minutes . If within the first minute of server restart I use !refresh command , server crashes ! this is really strange ! crash only happens in the first minute of warmup and only after I restart the server . Funny thing is , if I restart my server and then join server and change the map instantly , on the new map !refresh works properly and without any crashes .

There is something wrong within the first minute of starting the server and using !refresh command but I don't know what it is .

I would be thankful if you could have a look and fix these .

**Comment by mayersgamer** [comment]
removed the plugin and the server stopped crashing , 2 days of crashing every hour or so i tought it was the ram but no , it was the plugin .

**Comment by lostsoul6** [comment]
@mayersgamer read the 4th issue I reported above and see if it's the same for you . For me crash happens after server restart and doesn't happen if I change map after restarting server !
