### ISSUE TITLE
[REQ] Support for choosing knife

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#15]
I don't have a knife in my inventory, on the website I choose a knife and put the skin, but it doesn't show on the server.

How should I equip the knife with the skin I chose?

**Comment by exababy** [comment]
buy knife

**Comment by Nereziel** [comment]
For now use a plugin which change the base knife or find solution and share.

Odesláno z aplikace Outlook pro iOS<https://aka.ms/o0ukef>
________________________________
Od: crashzk ***@***.***>
Odesláno: Sunday, November 12, 2023 10:06:45 PM
Komu: Nereziel/cs2-WeaponPaints ***@***.***>
Kopie: Subscribed ***@***.***>
Předmět: [Nereziel/cs2-WeaponPaints] How to select knife skins (Issue #15)


I don't have a knife in my inventory, on the website I choose a knife and put the skin, but it doesn't show on the server.

How should I equip the knife with the skin I chose?

**Comment by crashzk** [comment]
Ok, leave some requests on GitHub and I'll be looking to implement them, for now thanks for the plugin

**Comment by rabi07** [comment]
@Nereziel

**Comment by rabi07** [comment]
@Nereziel

**Comment by Letaryat** [comment]
> Ok, leave some requests on GitHub and I'll be looking to implement them, for now thanks for the plugin

If you know how to implement choosing a default knife - I think that one of the best options would be a command in game which would give you a knife that you want for example: 
!knife karambit
!knife bayonet

Second option it would be nice to implement on website choosing a knife as a checkbox. So there would be a checkbox for selecting a knife. 
I would like to help but unfortunetly I don't know how to write code in C++, C#, CSSharp. Even when I tried to change a code a little bit it didn't work.

**Comment by Nereziel** [comment]
We can use also chat menu which is in cssharp.
![obrazek](https://github.com/Nereziel/cs2-WeaponPaints/assets/8618825/1aaa00e4-a232-4033-ae61-b59b09e2a1f9)

**Comment by Nereziel** [comment]
demo https://www.youtube.com/watch?v=2RpYFihaXE4

**Comment by daffyyyy** [comment]
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/41084667/b7be55bf-7066-4f6f-86fd-b37c4d6cff0a)
Not hard to implement via www, try yourself :P

**Comment by Nereziel** [comment]
Basic knife support added. Still needs some work.
