### ISSUE TITLE
Server crash on round restart

### ISSUE THREAD

**Issue by pedro639** [Nereziel/cs2-WeaponPaints#151]
MM 1282
CSS 166
cs2-WeaponPaints 184

The server crashes after round start, for example on a dm server after the warm-up round finishes and the game goes live. Or the same in a competitive / retakes server. Any situation where the server loads the map and the a round start happens.

I have tried to go back all the way to release 176 but it happens no matter what! I have also disabled all other plugins to check for incompatibility and it still happens so it can only be an issue directly related to cs2-WeaponPaints 

I am using my own website and not globalshare.

**Comment by Truyn** [comment]
similarly
