### ISSUE TITLE
The knife does not load

### ISSUE THREAD

**Issue by peyman8487777** [Nereziel/cs2-WeaponPaints#152]
Hello
The plugin is loaded correctly and the gun skin works correctly
But the knives don't work and the knife stops working as if we don't have a knife and when we change to the default it gets fixed.

**Comment by LinusFromArox** [comment]
is the server a retake server?

If so you have to go the config file /addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json

and change "GiveKnifeAfterRemove": false to true

**Comment by peyman8487777** [comment]
> is the server a retake server?
> 
> If so you have to go the config file /addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json
> 
> and change "GiveKnifeAfterRemove": false to true

no
This is a competitive server
I changed the GiveKnifeAfterRemove option to true, but it still has a problem

**Comment by LielXD** [comment]
Your server is probably on windows there is no fix for that for now.

**Comment by drakin001** [comment]
After changing 'GiveKnifeAfterRemove' to true, the knife resets to the default one after a few rounds

PS: I'm not using global share
