### ISSUE TITLE
plugin not working even tho its installed correctly

### ISSUE THREAD

**Issue by xSaqe** [Nereziel/cs2-WeaponPaints#154]
I installed the plugin correctly, its shown in css_plugins list command, i can see my server on the global website but the commands (!ws, !knife etc.) dont work. I also switched server guidelines to false. Server is hosted on linux. Any ideas why its not working?

**Comment by mihaps** [comment]
same issues, for now i use old v174 because for some reason its the only version that works (even tho v184 worked yesterday just fine)

**Comment by xSaqe** [comment]
> same issues, for now i use old v174 because for some reason its the only version that works (even tho v184 worked yesterday just fine)

i used the same build u mentioned and managed to make skins work but giving out knives doesnt work. when someone types !knife and than tries to pick one out it crashes whole server. have u had this problem and made it work somehow?

**Comment by asdfxD** [comment]
i had same issue when choose a knife the server crashes. delete database and create a new one sloves the issue.

**Comment by xSaqe** [comment]
> i had same issue when choose a knife the server crashes. delete database and create a new one sloves the issue.

is it just the Database.cs file? or do i need to do it some other way?

**Comment by asdfxD** [comment]
no, the mysql database in phpmyadmin. if you use global share, than it won't work cause u have no access to the database.

**Comment by xSaqe** [comment]
> no, the mysql database in phpmyadmin. if you use global share, than it won't work cause u have no access to the database.

ahhhh gotchu, i use global share but somehow it started to work just fine, the only downside is that u need to have default knife equiped idk why

**Comment by mihaps** [comment]
for me new versions still dont work and after last update using v174 server just crashes on round beginning 
(i use globalshare too)

**Comment by mihaps** [comment]
tho switching to server's database and globalshare false fixed the issue with new versions not working
