### ISSUE TITLE
This plugin needs fixing

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#155]
Hi @daffyyyy ,

can you please upload the version you yourself are using here ? because it can't be the latest release that you uploaded to github . The menus don't work .

in deagles for example we can't go to next page . !8 doesn't do anything . Also there was a bug with HUD (giving extra bombs) you said you'd fix .

I don't know which version to use . some older ones crash the server . some newer ones have other issues like above .

![wp](https://github.com/Nereziel/cs2-WeaponPaints/assets/127633547/d52aa27d-75f3-4b11-9913-d995f36432ff)

**Comment by lostsoul6** [comment]
@daffyyyy I couldn't check all of them but yeah most of them . for instance I had bayonet knife and wanted to choose the fade skin but when choosing it , nothing happened .

**Comment by daffyyyy** [comment]
> @daffyyyy I couldn't check all of them but yeah most of them . for instance I had bayonet knife and wanted to choose the fade skin but when choosing it , nothing happened .

I'll check later, ty for report
