### ISSUE TITLE
No weapons or first round crash with plugin cs2-retakes-allocator

### ISSUE THREAD

**Issue by st1ng2** [Nereziel/cs2-WeaponPaints#159]
Tried to compile with this fix [```if(weapon.Value.DesignerName == "weapon_knife") continue;```](https://github.com/yonilerner/cs2-retakes-allocator/commit/e48160eafa19040080a7d2c640dd9e94f0ac9442), but no luck. If possible, please fix.

**Comment by everkk** [comment]
Same problem
