### ISSUE TITLE
Question with website `config.php` file

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#16]
I would like to confirm that the `config.php` settings would be correct:
```
define('STEAM_DOMAIN_NAME', '');
define('STEAM_LOGOUT_PAGE', 'index.php');
define('STEAM_LOGIN_PAGE', 'index.php');
```

In this case, the Steam domain would be the one I registered **Steam API Key**?

And the options `STEAM_LOGOUT_PAGE` & `STEAM_LOGIN_PAGE` do I really put `index.php`?

**Comment by Nereziel** [comment]
It just redirects values to SteamConfig.php, for main funtionality you need only steamapi key.
https://github.com/Nereziel/cs2-WeaponPaints/blob/main/website/steamauth/SteamConfig.php
