### ISSUE TITLE
Can someone make a tutorial?

### ISSUE THREAD

**Issue by thegokussj337** [Nereziel/cs2-WeaponPaints#167]
Firstly ive uploaded the addon restarted the server so it can load and the plugin was loaded. In WeaponPaints.json i changed globalshare to true and followcs2guid idk to false. I filled the datahostname etc too and after that i was loggin in with my steam account on the website to see if my server is in it too. it was i used it and there was the menu. nothing changed i couldnt even use the command !ws or !knife any idea why?

**Comment by thegokussj337** [comment]
would be nice how?

**Comment by ViestursGeiko** [comment]
whats your dc

**Comment by thegokussj337** [comment]
gokusoloscityboyy

**Comment by Dobrik123** [comment]
The same problem. I don't know what to do anymore, the new versions don't work. The last working one was 176, but with the CSS update, the server crashed

**Comment by mayersgamer** [comment]
globalshare false 
 set database too

**Comment by asdfxD** [comment]
> globalshare false set database too

Does it work for you, also the knives? Knife works here but when killed and respawned i got default knife back and mostly the knife has a delay about 1-2 seconds to get it.

**Comment by mayersgamer** [comment]
> > globalshare false set database too
> 
> Does it work for you, also the knives? Knife works here but when killed and respawned i got default knife back and when it works, the knife has a delay about 1-2 seconds to get it with current version.

just installed the latest version ,  they removed globaleshare , everything works.

**Comment by drakin001** [comment]
if globalshare is on then there's no need to setup a database

Mine's working fine and i am not using globalshare

**Comment by Shadyy104** [comment]
> i can help

can you help me too? i don't know how to use any of this php stuff, i have installed the plugin but setting up the website i dont understand

**Comment by ShayannM** [comment]
shayan_m. can anyone hit me up on dc and help me its been 2 days i tried alot but couldnt get it started

**Comment by Nereziel** [comment]
better tutorial can be found at our discord server
