### ISSUE TITLE
Delay 2-3 seconds when issuing weapons

### ISSUE THREAD

**Issue by st1ng2** [Nereziel/cs2-WeaponPaints#176]
This has been happening since version 200+, can this be fixed?

**Comment by st1ng2** [comment]
to clarify, the weapon is first dropped and then picked up again, resulting in a 2-3 second delay )

**Comment by shaikhnedab** [comment]
try to revert to build 195 for now. its working absolutely fine for me

**Comment by everkk** [comment]
Same problem to me. On retake mode works very ugly. Build 195 works great but no glove save :/

**Comment by everkk** [comment]
Build 212 after update all works great
