### ISSUE TITLE
Issue : skins are not showing in server, also /knife not working 

### ISSUE THREAD

**Issue by rabi07** [Nereziel/cs2-WeaponPaints#18]
build with latest code useing API Version: 50
"WeaponPaints" (0.7) by Nereziel

Issue : skins are not showing in server, also /knife not working 

!ws !wp is working ( as its printing output in chat )

Already added FollowCS2ServerGuidelines to false

Previous build was working fine

Some one please confirm maybe only my issue xD

**Comment by shaikhnedab** [comment]
facing exactly same as above.
CSSharp api version 50

**Comment by daffyyyy** [comment]
New config file in counterstrikesharp/configs/plugins
and new .sql file

**Comment by exababy** [comment]
same
> New config file in counterstrikesharp/configs/plugins and new .sql file

**Comment by rabi07** [comment]
@daffyyyy
Is it working for you ?

I already configure my config file  which available in game/csgo/addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json
also added new sql

**Comment by daffyyyy** [comment]
Yes, works for me

**Comment by rabi07** [comment]
Is it possible to share the build here ,i have tried again its still same .

**Comment by Nereziel** [comment]
@rabi07 are you running it on windows server?

**Comment by exababy** [comment]
I think I understand it works on windows servers because windows build is taken.

**Comment by rabi07** [comment]
nope im running on linux

**Comment by exababy** [comment]
> nope im running on linux @Nereziel

pterodactyl not working ...

**Comment by daffyyyy** [comment]
> > nope im running on linux @Nereziel
> 
> only pterodactyl not working ...

I use pterodactyl and everything works
DM me on discord **daffyy** and maybe i can help you

**Comment by Nereziel** [comment]
Automated build is pushed, try from donwload from release and follow steps in readme.

**Comment by rabi07** [comment]
> > > nope im running on linux @Nereziel
> 
> > 
> 
> > only pterodactyl not working ...
> 
> 
> 
> I use pterodactyl and everything works
> 
> DM me on discord **daffyy** and maybe i can help you

Added - savage

**Comment by daffyyyy** [comment]
Problem found, hotfix will be available soon

**Comment by Nereziel** [comment]
try now
