### ISSUE TITLE
[BUG] Real gloves = default gloves

### ISSUE THREAD

**Issue by asdfxD** [Nereziel/cs2-WeaponPaints#181]
i got some reports at my servers that players own gloves are not visible ingame, also they have default gloves. happens only with this plugin loaded.

edit: indeed, tried it myself. equip real gloves and join server, the gloves are default.

**Comment by candied-apple** [comment]
It happens in knives to i have a knife but i've to remove it from loadout to be able to get knife from plugin.
When ever i go official mm i forget to equip my knife.

**Comment by asdfxD** [comment]
In Events.cs
                        
                        /*
			Server.NextFrame(() =>
			{
				RefreshGloves(player);
			});
                       */

real gloves are working with this and not replaced by default gloves, but you need to type !wp to sync gloves now.
