### ISSUE TITLE
[BUG] Plugin heavily affected by user skins.

### ISSUE THREAD

**Issue by candied-apple** [Nereziel/cs2-WeaponPaints#183]
The plugin affected by user owned equipped skins.
For example : If i equip a knife it wont give me knife in server.
If i own a skin and equip it will use that skin's float instead of server skin.

**Comment by crashzk** [comment]
Yes, everyone already [Known issues](https://github.com/Nereziel/cs2-WeaponPaints?tab=readme-ov-file#known-issues).

**Comment by candied-apple** [comment]
Weapon floats & stickers still effected in the new version.
