### ISSUE TITLE
[REQ] Remove `prefix` from `Config.cs` file

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#185]
https://github.com/Nereziel/cs2-WeaponPaints/blob/84adfa808532d3658db12e1627a903e00a76fe0c/Config.cs#L79-L80

Could it be removed right? Since **prefix** is now configured by the translation files.

**Comment by Oneycs** [comment]
The prefix was removed from the config. Dont know in what update.
