### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 1Mack** [Nereziel/cs2-WeaponPaints#19]
What u guys think about this [ inventory system?](https://github.com/ianlucas/cs2-inventory-simulator) 

I'm portabilizing it to working with [cs2-WeaponPaints](https://github.com/Nereziel/cs2-WeaponPaints)

**Comment by Nereziel** [comment]
Looks nice! I have made only very basic UI. Hope you will be able to port it

**Comment by 1Mack** [comment]
I'm working on it, but i don't have much time...in a few days/week im gonna publish a trial version 😍

**Comment by evanhzg** [comment]
@1Mack up ? :)
