### ISSUE TITLE
Tables are not created in the database. What am I doing wrong?

### ISSUE THREAD

**Issue by k1to0o** [Nereziel/cs2-WeaponPaints#190]
I tried the last 3 releases, the tables are not created anywhere
There are no errors in the console
And plugin is stuck in loading

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/155074657/fc7ebf5b-b166-4c6a-a417-a2e3e468bce5)
![chrome_zVPBk6RIHU](https://github.com/Nereziel/cs2-WeaponPaints/assets/155074657/055d66a2-214f-42f1-b9b5-369720548faf)
![chrome_p0kI4ePQUu](https://github.com/Nereziel/cs2-WeaponPaints/assets/155074657/f4e90a1f-2273-49be-a67a-55684fa3ecf4)

**Comment by candied-apple** [comment]
Make sure your credentials correct.

**Comment by k1to0o** [comment]
My credentials are correct. Local ip doesn't work. And the firewall doesn't block the port. 
I don't have a website. I used GlobalShare but it doesn't work anymore

> Make sure your credentials correct. Make sure your firewall does not block 3306 port. If you are running the database and server in the same machine try localhost as your host instead of ip.

**Comment by asdfxD** [comment]
maybe ur host does not allow remote connections, is it you own host?

**Comment by k1to0o** [comment]
The table for the Admin System plugin is created

> maybe ur host does not allow remote connections, is it you own host?

**Comment by k1to0o** [comment]
Solved a problem
