### ISSUE TITLE
Plugin stuck in loading

### ISSUE THREAD

**Issue by Meszyszu** [Nereziel/cs2-WeaponPaints#195]
So im not good at cs2 plugins. I followed this tutorial: https://www.youtube.com/watch?v=FlsKzStHJuY .
Idk what to do i just want to have fun with my friends and this isnt working and idk what to do.
If u want to give me any help please explain it.
[#1:LOADING]: "WeaponPaints" (2.2a) by Nereziel & daffyy
    Skin, gloves, agents and knife selector, standalone and web-based

I tried the newest version and the one before

**Comment by k1to0o** [comment]
I had the same problem, because the guide didn’t say where to put the files.
You have 2 files in your archive. You need to put WeaponPaints in the /game/csgo/addons/counterstrikesharp/plugins directory. You also have a gamedata and a file inside that you need to throw here /game/csgo/addons/counterstrikesharp/gamedata
These folders should look like this:

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/155074657/06f03d65-c54f-40cb-bc2d-bc67c9b6bfee)
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/155074657/f64c340d-c40c-481d-8cc3-4ebe245dd967)

After you have uploaded everything you need to open /game/csgo/addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json
And enter the database data. Before opening this folder you need to start the server at least 1 time

My config looks like this:
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/155074657/f458469a-b2ea-4e04-bc5c-a5df48540cf2)


After all this, you just start the server and enjoy the skins
Teams:
!skins
!knife
!gloves
!agents

**Comment by yichen11818** [comment]
```Failed to load plugin from C:\program files (x86)\steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\plugins\WeaponPaints\WeaponPaints.dll
System.Exception: Plugin "WeaponPaints.dll" requires a newer version of CounterStrikeSharp. The plugin expects version [178] but the current version is [166].
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 184
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34```   
and need version [178] of CounterStrikeSharp

**Comment by yichen11818** [comment]
> I had the same problem, because the guide didn’t say where to put the files.我遇到了同样的问题，因为指南没有说明将文件放在哪里。 You have 2 files in your archive. You need to put WeaponPaints in the /game/csgo/addons/counterstrikesharp/plugins directory. You also have a gamedata and a file inside that you need to throw here /game/csgo/addons/counterstrikesharp/gamedata 您的存档中有 2 个文件。您需要将WeaponPaints放在/game/csgo/addons/counterstrikesharp/plugins目录中。您还有一个游戏数据和一个文件，您需要将其扔到此处 /game/csgo/addons/counterstrikesharp/gamedata These folders should look like this: 这些文件夹应如下所示：
> 
> ![image](https://private-user-images.githubusercontent.com/155074657/310340833-06f03d65-c54f-40cb-bc2d-bc67c9b6bfee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDE3NzksIm5iZiI6MTcwOTgwMTQ3OSwicGF0aCI6Ii8xNTUwNzQ2NTcvMzEwMzQwODMzLTA2ZjAzZDY1LWM1NGYtNDBjYi1iYzJkLWJjNjdjOWI2YmZlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwODUxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTY2YmUzNzQ4NWZjYjUzMzY0Njc3MTljNzNkNWQzMjA2MTUwYmIyOGUyNWUxZmMzMTBiZWFkNTU0OWUyZGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GJxlbn2zXHUwJgL_KGRnrkMFYrSRmUlHJNwzqKVF6NY) ![image](https://private-user-images.githubusercontent.com/155074657/310340947-f64c340d-c40c-481d-8cc3-4ebe245dd967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDE3NzksIm5iZiI6MTcwOTgwMTQ3OSwicGF0aCI6Ii8xNTUwNzQ2NTcvMzEwMzQwOTQ3LWY2NGMzNDBkLWM0MGMtNDgxZC04Y2MzLTRlYmUyNDVkZDk2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwODUxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDMzY2VhZWVjZGU5MDRkZmIzMzQ3MzMxZjA1ZWVkNTRhZWViMDllZGQ0ZGU1NzYxOGZjMjBjNTc1NjMxZmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UqfL9eniyLyZ6W1qqsU4gZi2bkZyjzcT2pz53Z-GibM)
> 
> After you have uploaded everything you need to open /game/csgo/addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json上传所需的所有内容后，打开 /game/csgo/addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json And enter the database data. Before opening this folder you need to start the server at least 1 time 并输入数据库数据。在打开此文件夹之前，您需要启动服务器至少 1 次
> 
> My config looks like this:我的配置如下： ![image](https://private-user-images.githubusercontent.com/155074657/310341458-f458469a-b2ea-4e04-bc5c-a5df48540cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDE3NzksIm5iZiI6MTcwOTgwMTQ3OSwicGF0aCI6Ii8xNTUwNzQ2NTcvMzEwMzQxNDU4LWY0NTg0NjlhLWIyZWEtNGUwNC1iYzVjLWE1ZGY0ODU0MGNmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwODUxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTVmOGVjZWVlODI4ZjQ4Mjc3NGJhNDIyNTY5MDMwZGFkYjE5OTU0NzM4YWY1OTQ2NjQ2OTE2MzM0ZmM2MzBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NVeTeraH9pc08dfLWpFhg4JUiA8VrIQZgzgN8GgvfEU)
> 
> After all this, you just start the server and enjoy the skins完成所有这些后，您只需启动服务器并享受皮肤 Teams: 团队： !skins  !皮肤 !knife  ！刀 !gloves  ！手套 !agents  ！代理

why your Version is 6.its that right

**Comment by fuzzyscn** [comment]
win need use last version 2.1a

**Comment by yichen11818** [comment]
> win need use last version 2.1a

同windows 我发现新版会导致内存调用错误 您所指的2.1a是什么

**Comment by fuzzyscn** [comment]
> > win need use last version 2.1a
> 
> 同windows 我发现新版会导致内存调用错误 您所指的2.1a是什么

build 214

**Comment by leplaque** [comment]
> I had the same problem, because the guide didn’t say where to put the files. You have 2 files in your archive. You need to put WeaponPaints in the /game/csgo/addons/counterstrikesharp/plugins directory. You also have a gamedata and a file inside that you need to throw here /game/csgo/addons/counterstrikesharp/gamedata These folders should look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/155074657/310340833-06f03d65-c54f-40cb-bc2d-bc67c9b6bfee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDkzMzQsIm5iZiI6MTcxMDcwOTAzNCwicGF0aCI6Ii8xNTUwNzQ2NTcvMzEwMzQwODMzLTA2ZjAzZDY1LWM1NGYtNDBjYi1iYzJkLWJjNjdjOWI2YmZlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMDU3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTI0MmQxNjc1M2VjZDFjYTAyZmNlZDQ2N2FhOGI5YmRjZmUzZGFhM2FkMmFmMTkxZWE1NmIzNDYyZjkzMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.157QaxLFVtz944j7TgLfVw74p7BaYvbWoZrH-JpeNjU) ![image](https://private-user-images.githubusercontent.com/155074657/310340947-f64c340d-c40c-481d-8cc3-4ebe245dd967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDkzMzQsIm5iZiI6MTcxMDcwOTAzNCwicGF0aCI6Ii8xNTUwNzQ2NTcvMzEwMzQwOTQ3LWY2NGMzNDBkLWM0MGMtNDgxZC04Y2MzLTRlYmUyNDVkZDk2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMDU3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDcxYWEzZDVkYWE5NjQ3MTBlYzBkYWJlYmM1ZTQxZTBkYjZhNzA1NjlkYWQ1NzA3YTA1M2YxNDEwYjY3ODY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.18aUNgXkNehxzVunVGepBhuP-QIfb-PWwfi7rLSVnRE)
> 
> After you have uploaded everything you need to open /game/csgo/addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json And enter the database data. Before opening this folder you need to start the server at least 1 time
> 
> My config looks like this: ![image](https://private-user-images.githubusercontent.com/155074657/310341458-f458469a-b2ea-4e04-bc5c-a5df48540cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDkzMzQsIm5iZiI6MTcxMDcwOTAzNCwicGF0aCI6Ii8xNTUwNzQ2NTcvMzEwMzQxNDU4LWY0NTg0NjlhLWIyZWEtNGUwNC1iYzVjLWE1ZGY0ODU0MGNmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMDU3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWMyZmVkMzQ5MzMzYzY2ZWM0N2Y2NTc1NDdkYWQwOWVkNDZmMzg1OGY3N2FlOTE1ZDQwNTQ3YTBhMGNlNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lNwmTB96LrVDZ35T16jxwa0-xvoNvUmxPBGjAqQF52s)
> 
> After all this, you just start the server and enjoy the skins Teams: !skins !knife !gloves !agents

bro which database should i put
