### ISSUE TITLE
[REQ] Use HTML Center Menus not chat menus

### ISSUE THREAD

**Issue by candied-apple** [Nereziel/cs2-WeaponPaints#197]
i think html center menus better option to select knife glove skin agent etc.

**Comment by asdfxD** [comment]
no

**Comment by candied-apple** [comment]
@asdfxD did you even understand what i'm meaning. I'm talking about this.
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/50497574/9f63e8ae-dc5b-41b5-bca6-ee70e6d72899)

**Comment by crashzk** [comment]
I believe that as an option to activate/deactivate this feature it would be perfect, so we decide how to use it on the server, whether you prefer Chat or Center.

`"UseCenterHtmlMenu": true or false`
