### ISSUE TITLE
Where should I put the file with the site?

### ISSUE THREAD

**Issue by k1to0o** [Nereziel/cs2-WeaponPaints#199]
I'm stupid, where should I put the file with the site?

**Comment by ShayannM** [comment]
im stupid aswell please help

**Comment by qaziabdullah** [comment]
Use Xampp and set the website in localhost. You can use port forwarding for the other players in your server.

**Comment by fr0sty98** [comment]
> Use Xampp and set the website in localhost. You can use port forwarding for the other players in your server.

Can you please explain how to do that ? What localhost ?

**Comment by Nereziel** [comment]
You can find tutorials on net how to run website.
