### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by Aliyuyu** [Nereziel/cs2-WeaponPaints#20]
Parse error: syntax error, unexpected '=' in D:\phpstudy_pro\WWW\class\database.php on line 13

$result ??= false; ？？？

**Comment by Nereziel** [comment]
php version > 8 ?

**Comment by daffyyyy** [comment]
Change to $result ?? false;

**Comment by Aliyuyu** [comment]
> PHP 版本 > 8 ？

8.2.9

**Comment by Aliyuyu** [comment]
> 更改为 $结果 ?? 错误的;



> Change to $result ?? false;

after 
Fatal error: Uncaught Error: Undefined constant PDO::MYSQL_ATTR_INIT_COMMAND in D:\phpstudy_pro\WWW\class\database.php:7 Stack trace: #0 D:\phpstudy_pro\WWW\index.php(6): DataBase->__construct() #1 {main} thrown in D:\phpstudy_pro\WWW\class\database.php on line 7

**Comment by daffyyyy** [comment]
You probably changed something/pasted it wrong.
I checked the current database.php and everything works.
Paste the contents of this file again
https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/class/database.php

**Comment by Aliyuyu** [comment]
网站已经正常  游戏皮肤未改变
![122](https://github.com/Nereziel/cs2-WeaponPaints/assets/40660884/e14c4917-64f3-4707-9a3f-a6168cd58037)

**Comment by Aliyuyu** [comment]
The website is now normal and the skin in the game has not changed.
![1](https://github.com/Nereziel/cs2-WeaponPaints/assets/40660884/2b87d18e-74d7-4a88-b970-795593039750)

**Comment by Aliyuyu** [comment]
> The website is now normal and the skin in the game has not changed. ![1](https://user-images.githubusercontent.com/40660884/282809743-2b87d18e-74d7-4a88-b970-795593039750.png)

Solved, the default skin can only be modified
