### ISSUE TITLE
Bug music kits and animation knife

### ISSUE THREAD

**Issue by Ankerin** [Nereziel/cs2-WeaponPaints#221]
А bug with music was noticed, it does not work for those who already have music kits. And another bug, if you hold down the reload weapon, when examining the knife, the animation accelerates.

**Comment by asdfxD** [comment]
some of the knives have really bugged animations when you drop them, when holding the butterfly its bugged too for others. some other knives are working fine m9, karambit, bowie... dunno why.

stiletto example.
[k.webm](https://github.com/Nereziel/cs2-WeaponPaints/assets/24253340/77c13ba5-5878-45ad-8be9-cb7e40309c82)
