### ISSUE TITLE
Skins not changing

### ISSUE THREAD

**Issue by candyman6996** [Nereziel/cs2-WeaponPaints#223]
i used my friends configs and everything, its working fine on his server but not on mine, menus are opening and everything but the skins, knife, gloves nothing is changing any fix i saw a post saying to try removing the database can anyone guide me how ? i am using without sql

**Comment by candyman6996** [comment]
![Screenshot 2024-03-24 215545](https://github.com/Nereziel/cs2-WeaponPaints/assets/164777671/ee466179-954e-4a31-ba79-4f014f106f16)
I have narrowed down it to here can anyone help how to configure this ?

**Comment by mrc4tt** [comment]
You must set up your database credentials, or it will not work. :-)

**Comment by Korabi123** [comment]
> You must set up your database credentials, or it will not work. :-)

what do i put in at DatabaseHost?

**Comment by cardosomarcos** [comment]
> > You must set up your database credentials, or it will not work. :-)
> 
> what do i put in at DatabaseHost?

It's necessary to have a database to use the skins, if you don't you need to hire someone that provides this service for you.
If you already have, you just need to fill the file with the database information. 
Like
"DatabaseHost" : "yourdatabasehost",
"DatabaseUser : "usernamethatwascreatedforyoudatabase"
.....
