### ISSUE TITLE
[BUG] Knife skin disappears when knife round is on with MatchZy plugin

### ISSUE THREAD

**Issue by walidbouachir** [Nereziel/cs2-WeaponPaints#224]
Repro steps:

1. install the plugin cs2-WeaponPaints [https://github.com/Nereziel/cs2-WeaponPaints](url)
2. install the plugin MatchZy [https://github.com/shobhit-pathak/MatchZy](url)
3. go into the server and chose your knife skin
4. start the knife round with MatchZy plugin

**Expected result:** The knife skin is working fine
**Result:** The knife skin is changed to the default knife skin

Something is wrong with either this plugin or MatchZy plugin. Any fix for this soon?

**Comment by Jyun5978** [comment]
I posted a similar issue and left a comment here, hoping that the author will see one of the posts.
外掛程式清單：
[MatchZy](https://github.com/shobhit-pathak/MatchZy)
[CS2-RockTheVote](https://github.com/abnerfs/cs2-rockthevote)
[CS2-SimpleAdmin](https://github.com/daffyyyy/CS2-SimpleAdmin)

將此外掛程式與 Matchyz 一起使用。雖然開始刀輪皮膚會變成香草，但刀類（我選擇了 BTFK Ruby，但在刀輪期間，它將是香草 btfk）將是相同的。當你檢查皮膚時（比如反覆按壓fr）。有可能發生錯誤。（就像我張貼的照片一樣）
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/22559124/c96a6019-fbfe-4b5c-ae80-c366d702938e)


如果一些玩家已經裝備了自己的手套。手套命令無法正常工作。
即使在聊天中鍵入 ！wp 命令，手套也不會改變。

**Comment by walidbouachir** [comment]
@Nereziel could you please look at this issue and tell us if it's coming from this plugin or [MatchZy ](https://github.com/Nereziel/cs2-WeaponPaints/issues/url) one?
