### ISSUE TITLE
Long frame every 4-5 seconds

### ISSUE THREAD

**Issue by johandrevwyk** [Nereziel/cs2-WeaponPaints#225]
Im running Retakes with all the latest versions as of today (css 202)

And every 4-5 seconds the server gets a long frame of 16ms.

Yes I know its weaponpaints, because long frames stops the moment I unload plugin.

No its not the server hardware because I have many other servers running on the same hardware and there are no issues.

**Comment by daffyyyy** [comment]
Tested, not possible with wp
