### ISSUE TITLE
No OpenID Server

### ISSUE THREAD

**Issue by neo-yan** [Nereziel/cs2-WeaponPaints#228]
I use the 'WeaponPaints-Website'
Then I need to log in steam on the web page
But the following error message appears on the page

Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /www/wwwroot/web/steamauth/openid.php on line 190

Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /www/wwwroot/web/steamauth/openid.php on line 320

Warning: get_headers(https://steamcommunity.com/openid): Failed to open stream: Connection refused in /www/wwwroot/web/steamauth/openid.php on line 416

Warning: file_get_contents(https://steamcommunity.com/openid): Failed to open stream: Connection refused in /www/wwwroot/web/steamauth/openid.php on line 447

Warning: file_get_contents(https://steamcommunity.com/openid): Failed to open stream: Connection refused in /www/wwwroot/web/steamauth/openid.php on line 447
No OpenID Server found at https://steamcommunity.com/openid

Is there something wrong with my Internet ？

**Comment by neo-yan** [comment]
![error](https://github.com/Nereziel/cs2-WeaponPaints/assets/54460041/2899c100-fed7-493a-99e2-5bd858e9d787)

**Comment by Nereziel** [comment]
try use other 3rd party website for wp
