### ISSUE TITLE
Newest Build will not upload to  dathost plugins? Anyway to fix, 

### ISSUE THREAD

**Issue by andersontvcs2** [Nereziel/cs2-WeaponPaints#232]
Its stuck on 1/1 Plugins Loading for over 5 hours now.

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/156965837/dcb308d3-5ae3-478a-a4f3-e2a6cf506707)

**Comment by hassann1122** [comment]
hello were you able to figure it out or helo me setting up my plugin on dathost servers ?

**Comment by daffyyyy** [comment]
Hosting issue
