### ISSUE TITLE
Add pattern titles for skins (Ruby, Sapphire, Blue gem, etc.)

### ISSUE THREAD

**Issue by shmitzas** [Nereziel/cs2-WeaponPaints#236]
Would be very useful for players to see which doppler is a Ruby, Sapphire, Black pearl, etc. Also this naming logic could be applied to other skins (like blue gem Case Hardened).

**Comment by Liubik** [comment]
you can edit the skins.json file and change it manually in there, if you'd like I'll send you a portion of mine, I already did a bit of what you're talking about.

**Comment by shmitzas** [comment]
That would be very useful, could you paste it here?

**Comment by Liubik** [comment]
{
		"weapon_defindex": 500,
		"weapon_name": "weapon_bayonet",
		"paint": "415",
		"image": "https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/img/skins/weapon_bayonet-415.png",
		"paint_name": "★ Bayonet | Doppler Ruby"
	},
	{
		"weapon_defindex": 500,
		"weapon_name": "weapon_bayonet",
		"paint": "416",
		"image": "https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/img/skins/weapon_bayonet-416.png",
		"paint_name": "★ Bayonet | Doppler Sapphire"
	},
	{
		"weapon_defindex": 500,
		"weapon_name": "weapon_bayonet",
		"paint": "417",
		"image": "https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/img/skins/weapon_bayonet-417.png",
		"paint_name": "★ Bayonet | Doppler Black Pearl"
	},
	{
		"weapon_defindex": 500,
		"weapon_name": "weapon_bayonet",
		"paint": "418",
		"image": "https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/img/skins/weapon_bayonet-418.png",
		"paint_name": "★ Bayonet | Doppler Phase 1"
	},
	{
		"weapon_defindex": 500,
		"weapon_name": "weapon_bayonet",
		"paint": "419",
		"image": "https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/img/skins/weapon_bayonet-419.png",
		"paint_name": "★ Bayonet | Doppler Phase 2"
	},
	{
		"weapon_defindex": 500,
		"weapon_name": "weapon_bayonet",
		"paint": "420",
		"image": "https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/img/skins/weapon_bayonet-420.png",
		"paint_name": "★ Bayonet | Doppler Phase 3"
	},
	{
		"weapon_defindex": 500,
		"weapon_name": "weapon_bayonet",
		"paint": "421",
		"image": "https://raw.githubusercontent.com/Nereziel/cs2-WeaponPaints/main/website/img/skins/weapon_bayonet-421.png",
		"paint_name": "★ Bayonet | Doppler Phase 4"
	},

**Comment by shmitzas** [comment]
Other patterns (like Emerald doppler) can be easily found here [https://totalcsgo.com/codes/skin-ids](https://totalcsgo.com/codes/skin-ids)
