### ISSUE TITLE
[REQ] Stickers and their customization

### ISSUE THREAD

**Issue by TropieRi** [Nereziel/cs2-WeaponPaints#238]
By using the already defined function "CAttributeList_SetOrAddAttributeValueByName" we can put stickers on the weapons and customize their wear, rotation, and position. Below is the code for doing mentioned stuff, do whatever you please with the info:

```
public float ViewAsFloat(uint value)
{
	byte[] bytes = BitConverter.GetBytes(value);
	return BitConverter.ToSingle(bytes, 0);
}

CAttributeList_SetOrAddAttributeValueByName.Invoke(weapon.AttributeManager.Item.NetworkedDynamicAttributes.Handle, $"sticker slot {x} id", ViewAsFloat((uint)60));

CAttributeList_SetOrAddAttributeValueByName.Invoke(weapon.AttributeManager.Item.NetworkedDynamicAttributes.Handle, $"sticker slot {x} rotation", 180f);

CAttributeList_SetOrAddAttributeValueByName.Invoke(weapon.AttributeManager.Item.NetworkedDynamicAttributes.Handle, $"sticker slot {x} offset x", 0.08f);

CAttributeList_SetOrAddAttributeValueByName.Invoke(weapon.AttributeManager.Item.NetworkedDynamicAttributes.Handle, $"sticker slot {x} offset y", 0.04f);

CAttributeList_SetOrAddAttributeValueByName.Invoke(weapon.AttributeManager.Item.NetworkedDynamicAttributes.Handle, $"sticker slot {x} wear", 0.0001f);
```

The position is calculated from the sticker slot x + or - the offset

Which results to do this:
![20240413104014_1](https://github.com/Nereziel/cs2-WeaponPaints/assets/40918225/fb8da0f0-aaf8-498a-a1ba-008fe6d7a345)

**Comment by samyycX** [comment]
Can you update the stickers on a same paint? I do get the stickers with this method, but I can't get it updated without changing a paint or reconnecting the server.

**Comment by Kaysharp42** [comment]
I tried your solution and it works fine except when I try to change the stickers. They stay the same until I restart the server or rejoin the server.

**Comment by originalaidn** [comment]
added with keychains in 2.6a release
