### ISSUE TITLE
player by anything,server crashed

### ISSUE THREAD

**Issue by NoSetViolin** [Nereziel/cs2-WeaponPaints#242]
i run plugins, everything looks great, when i buy weapons, server crashed like this 
![8345195e51d08bacd58bb073a4fe0255](https://github.com/Nereziel/cs2-WeaponPaints/assets/130219679/31ef9d10-1410-42a5-a8ae-03439f81e7a5)

**Comment by zzojbk** [comment]
Mine is a direct server shutdown，Then how do you generate the weapon skin you want?

**Comment by fuzzyscn** [comment]
win server need use 2.3a !

**Comment by yichen11818** [comment]
这是来自QQ邮箱的自动回复邮件。你好，已收到您的邮件。

**Comment by NoSetViolin** [comment]
> win server need use 2.4a !

What is 2.4a! Please tell me thx!!!

**Comment by fuzzyscn** [comment]
> > win server need use 2.4a !
> 
> What is 2.4a! Please tell me thx!!!

plugins version.

**Comment by NoSetViolin** [comment]
> > > win server need use 2.4a !
> > 
> > What is 2.4a! Please tell me thx!!!
> 
> plugins version.

Witch plugins pls,I'm noob T_T

**Comment by fuzzyscn** [comment]
> > > > win server need use 2.4a !
> > > 
> > > 
> > > What is 2.4a! Please tell me thx!!!
> > 
> > 
> > plugins version.
> 
> Witch plugins pls,I'm noob T_T

this build-252 is 2.4a!

**Comment by NoSetViolin** [comment]
> > > > > win server need use 2.4a !
> > > > 
> > > > 
> > > > What is 2.4a! Please tell me thx!!!
> > > 
> > > 
> > > plugins version.
> > 
> > 
> > Witch plugins pls,I'm noob T_T
> 
> this build-252 is 2.4a!

thanks!!!! i goto try it thanks a lot !!!!!!!

**Comment by NoSetViolin** [comment]
> > > > > win server need use 2.4a !
> > > > 
> > > > 
> > > > What is 2.4a! Please tell me thx!!!
> > > 
> > > 
> > > plugins version.
> > 
> > Witch plugins pls,I'm noob T_T
> 
> this build-252 is 2.4a!

IT WORKS!!! THANKS BRO I LOVE U SO MUCH
