### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by Carloscb22** [Nereziel/cs2-WeaponPaints#243]
WeaponPaints.json:

  "DatabaseHost": "localhost",
  "DatabasePort": 3306,
  "DatabaseUser": "(my userdatabase)",
  "DatabasePassword": "(my password)",
  "DatabaseName": "(my userdatabasename)",
  "CmdRefreshCooldownSeconds": 60,
  "Prefix": "[WeaponPaints]",
  "Website": "theripperscs.com.ar/skins",

config.php:
`<?php
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', '(my db_name)');
define('DB_USER', '(my db_user)');
define('DB_PASS', '(my db_pass)');

define('WEB_STYLE_DARK', true);

define('STEAM_API_KEY', '(my api_key)');
define('STEAM_DOMAIN_NAME', '');
define('STEAM_LOGOUT_PAGE', '');
define('STEAM_LOGIN_PAGE', '');`

I fill in the data that way but when I enter the website it appears that I log in to Steam I do it and at the time of loading my website throws an error, could someone tell me that I am doing wrong?

**Comment by 420michalz** [comment]
What's the error?

**Comment by Carloscb22** [comment]
![Captura de pantalla 2024-04-20 033852](https://github.com/Nereziel/cs2-WeaponPaints/assets/165312190/3d11eac4-4d7f-4039-8055-673814a4d9d8)

![1](https://github.com/Nereziel/cs2-WeaponPaints/assets/165312190/8be7654b-8ddc-4641-ace8-9a0fc21def4e)

![Captura de pantalla 2024-04-20 033736](https://github.com/Nereziel/cs2-WeaponPaints/assets/165312190/2d2fdff4-66d2-44cf-84be-822dd1a81ee3)

**Comment by Carloscb22** [comment]
When I try to log in, the web page when loading issues that error

**Comment by iWanheda** [comment]
well provide us with some logs

**Comment by Carloscb22** [comment]
Apologies I'm pretty new to all of this, how could I look up the error log?

**Comment by Carloscb22** [comment]
23:32:04 [EROR] (plugin:WeaponPaints) Unable to connect to database: Connect Timeout expired.

**Comment by Carloscb22** [comment]
| | _ | || || _ || || || | | || || _ || | | | | || || |
| || || || || || || _ || _ || || || _ || || || | | || || || __|
| || | | || || || | | || || || || || | | | | | | |_____
| || || || || || || _ || || || | | _ | | | | |
| _ || | | _ || | | || | | || | | _ || | | | | | | | _| |
|| |||||| |||| |||| |||| || |||| || || || |______|
>> Version: 2.4b
>> GitHub: https://github.com/Nereziel/cs2-WeaponPaints

00:23:43 [INFO] (plugin:WeaponPaints) Plugin is up to date

00:23:58 [EROR] (plugin:WeaponPaints) Unable to connect to database: Connect Timeout expired.
