### ISSUE TITLE
Use force full update to update skins

### ISSUE THREAD

**Issue by samyycX** [Nereziel/cs2-WeaponPaints#245]
bober has found a way to force a full update on player, and he posted the code in counterstrikesharp official discord:
https://discord.com/channels/1160907911501991946/1175947333880524962/1231712355784851497

I have tested that this method can update the skins

I believed that with this method we can update the skin faster, and solve some problems caused by current update method

**Comment by mrc4tt** [comment]
You're welcome to make PR =)

**Comment by samyycX** [comment]
A problem here:
skin name and knife icon cant be updated if just invoke the forcefullupdate
