### ISSUE TITLE
Skins don't work

### ISSUE THREAD

**Issue by NatsuPT** [Nereziel/cs2-WeaponPaints#249]
I have 2 servers, in one of them everything works perfectly. But in the other one skins don't work. Only thing working are agents.
Anyone knows what the problem is?

**Comment by UmerNaZavode** [comment]
did you remember to change core.json?

**Comment by NatsuPT** [comment]
> did you remember to change core.json?

Yeah, I did. But I unisntalled the plugin once and it is working now. Not sure what I did wrong but its working now. Ty for trying to help.
