### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by chycken** [Nereziel/cs2-WeaponPaints#26]
Hello.
Can you add a new command into config so I can turn off the !ws function (and wont write to the chat that !ws exists). 
I dont have any website, so cant use the !ws, and this is unnecessary to me on my server.
Or is it possible to do this plugin a way that we don't need a website etc.?

**Comment by Nereziel** [comment]
Then why you need this plugin if you can't change paints? (maybe i got the question wrong?)

Its possible to make commands that change the paints, etc., but i won't do it. (atleast now)

**Comment by chycken** [comment]
The !knife is enough for me, thats why im asking you for a command which helps me to turn off the !ws . 

If you will do the plugin a way that we dont need website, !ws will simply work, than I'd gladly pay for that plugin (and I believe other people too)

**Comment by daffyyyy** [comment]
Don't use the site? Then players will not be able to use skins

**Comment by chycken** [comment]
I know, but it says in the chat that te !ws is avialable. Id like to turn it off

**Comment by Nereziel** [comment]
The plugin is not announcing anything unless player types command.
But you can remove the whole command and compile plugin for now.

**Comment by chycken** [comment]
I dont understand it that much, but thanks.
Looking forward for the next version, when once youll make it a way without using website.

**Comment by Nereziel** [comment]
command in config
