### ISSUE TITLE
Problems with new WP update

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#263]
Hi @daffyyyy ,

After updating the plugin to be compatible with latest CS2 update , I noticed 3 issues :

1- Knives don't show selected skins . For example when I choose the Fade skin to butterfly knife , it just shows the default butterfly knife skin .

![wp-knife](https://github.com/Nereziel/cs2-WeaponPaints/assets/127633547/c55b4a38-2534-46a4-b10d-f2439a19b42b)

2- when I select a skin for a gun that I haven't purchased , for a second or so , I saw that the player model hands have disappeared . for instance , If you look at the picture below , I don't own an AK47 in the round and when I selected an AK47 skin , this below bug appeared in player model hands : 

![wp-skin-bug](https://github.com/Nereziel/cs2-WeaponPaints/assets/127633547/953bb839-d52e-4c10-9ea5-5d82f6754570)

3- Also for some skins , when selecting the skin , the preview picture is not shown . 

Would be really thankful if you could solve the issues described . thank you .

**Comment by asdfxD** [comment]
No issues here on linux, sharp 235 & meta 1293.

Your OS?

**Comment by lostsoul6** [comment]
> No issues here on linux, sharp 235 & meta 1293.
> 
> Your OS?

I'm on the same config as yours . Linux with CSS 235 and MM1293 . 

You mentioned this a few days ago : 

https://github.com/Nereziel/cs2-WeaponPaints/issues/260#issuecomment-2131156480

Also I'm using the latest build (269) . what build are you using ?

**Comment by lostsoul6** [comment]
do have show skin image true in config ? or have u set it to false? 

also did you check point number 2 in my first message? I mean the one where hand model disappears if you select skin for a gun that you haven't purchased in the round .

well I have the issues I described above so I opened an issue . let's see what @daffyyyy says about it .

**Comment by ianlucas** [comment]
Is issue 1 only happening for Fade or other paints as well?

**Comment by asdfxD** [comment]
@lostsoul6 no, i set skin image to false and no, i don't have any issues. everything works as it should.
