### ISSUE TITLE
Bug KNIFE

### ISSUE THREAD

**Issue by kauanlsbarreto** [Nereziel/cs2-WeaponPaints#268]
When choosing a knife, it's not working, it's not going with the SKIN and when you put the knife that I put on the skin on, even the TR knife, it looks like the CT knife

**Comment by stefanx111** [comment]
update your gamedata from `addons/counterstrikesharp/gamedata/weaponpaints.json` with this [weaponpaints.json](https://github.com/Nereziel/cs2-WeaponPaints/blob/main/gamedata/weaponpaints.json)

**Comment by kauanlsbarreto** [comment]
Perfect, fixed it, thank you

**Comment by kauanlsbarreto** [comment]
Is it possible to give permission to change skin only if it has a flag?

**Comment by vTeee** [comment]
The knife paint doesn’t load up other than that everything works fine but knife . Replaced the game data file with the above one and still it doesn’t fix any advise?!?

**Comment by daffyyyy** [comment]
Disable your own knife
