### ISSUE TITLE
Only thing I can change is the knife

### ISSUE THREAD

**Issue by AngelBePro** [Nereziel/cs2-WeaponPaints#274]
So It took me a while to realize I need a database like mySQL. After installing it and setting up credentials and steam api key, when I tried changing weapon skins nothing changed. Same with gloves. only thing that changes is the knife. And only the knife, since paints don't work. I don't see any errors tho.

**Comment by tommiczek** [comment]
post your console logs when changing skins

**Comment by AngelBePro** [comment]
I fixed it by reinstalling the server, maybe I somehow didnt set FollowCS2Guidelines = false
