### ISSUE TITLE
[REQ] Add offline support /cannot connect (raw.githubusercontent.com:443)

### ISSUE THREAD

**Issue by 986823307** [Nereziel/cs2-WeaponPaints#279]
![屏幕截图 2024-06-21 172328](https://github.com/Nereziel/cs2-WeaponPaints/assets/56620683/ea16186f-baee-4288-bdbe-173c7cc88647)

**Comment by nicedayzhu** [comment]
it‘s just the common issue for people who lives in mainland China, github connection always reset by your ISP
