### ISSUE TITLE
Gloves

### ISSUE THREAD

**Issue by LucHawes** [Nereziel/cs2-WeaponPaints#281]
Hi, whenever i have real gloves equipped, the skin changer doesn't work, and just shows my own gloves. It will only work if i equip default gloves. 
Any idea how to solve this?

**Comment by asdfxD** [comment]
It's normal i guess cause few weeks ago, everyone who used their own inventory gloves gets the cs2 default gloves from the plugin when they join a server with weaponpaints plugin.
