### ISSUE TITLE
Fatal Error on website

### ISSUE THREAD

**Issue by bboynico22** [Nereziel/cs2-WeaponPaints#284]
I get this after logging into Steam on the website, I apologize if the question is stupid, I'm new to this.

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'defaultdb.wp_player_skins' doesn't exist in /storage/ssd2/530/22364530/public_html/class/database.php:18 Stack trace: #0 /storage/ssd2/530/22364530/public_html/class/database.php(18): PDOStatement->execute() #1 /storage/ssd2/530/22364530/public_html/index.php(14): DataBase->select() #2 {main} thrown in /storage/ssd2/530/22364530/public_html/class/database.php on line 18

**Comment by L1teD** [comment]
You need firstly run the plugin, it'll create needed tables and only then you can use the website

**Comment by Nereziel** [comment]
Answered by @L1teD
