### ISSUE TITLE
ERROR on server

### ISSUE THREAD

**Issue by fr0sty98** [Nereziel/cs2-WeaponPaints#285]
Hello,
I have installed plugin correctly using tutorial I found on google and tested in console, it's giving info that it's loaded correctly but when I type !ws !knife whatever, nothing happens on server.

```
css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1:LOADING]: "WeaponPaints" (2.5a) by Nereziel & daffyy
    Skin, gloves, agents and knife selector, standalone and web-based
```

I noticed that server is giving this error, does anyone know what's going on ? Web database is installed and working, but when I click on default knife and change to something else, it gets back to default immediately

`14:36:51 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'WeaponPaints.WeaponPaints' threw an exception.
 ---> System.ArgumentException: Method CAttributeList_SetOrAddAttributeValueByName not found in gamedata.json
   at CounterStrikeSharp.API.Core.GameData.GetSignature(String key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GameData.cs:line 94
   at WeaponPaints.WeaponPaints..cctor() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 98
   --- End of inner exception stack trace ---
   at WeaponPaints.WeaponPaints.OnPlayerDisconnect(EventPlayerDisconnect event, GameEventInfo info) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 73
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100`

**Comment by mrc4tt** [comment]
It says you didn't installed all files from the zip folder =)

You forgot to install gamedata from WeaponPaints.

**Comment by fr0sty98** [comment]
> It says you didn't install all files from the zip folder =)
> 
> You forgot to install gamedata from WeaponPaints.
> 
> ![image](https://private-user-images.githubusercontent.com/5301047/342735877-20df1c45-332e-4503-9db6-3ea1d1831315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMjEwMzIsIm5iZiI6MTcxOTMyMDczMiwicGF0aCI6Ii81MzAxMDQ3LzM0MjczNTg3Ny0yMGRmMWM0NS0zMzJlLTQ1MDMtOWRiNi0zZWExZDE4MzEzMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMTMwNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmViMzMxODliMDYzNjQzMDBlMjg2YjFlZTQwODBmMmM1YmY1ZWYyMTJlZmRkNDhhMzRkMmI0MGQ2YWE3M2YxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m8_rSo99APyGkXRWuwIgmWcu-C38l5c0F2p65of0zXk) Make sure the first folder (gamedata) - insert it to `addons/counterstrikesharp/`
> 
> WeaponPaints insert it to this: `addons/counterstrikesharp/plugins/`

Thank you very much, gamedata folder was an issue.
Now I'm confused about database. I have my own website but it's cheapest plan with only 1 database, and I tryed to connect it and it was a failure. Hosting told me that remote database connections are not allowed on shared hosting servers.
What hosting are you using for database ?

```
15:04:07 [EROR] (plugin:WeaponPaints) Unable to connect to database: Unable to connect to any of the specified MySQL hosts.
An error occurred: Unable to connect to any of the specified MySQL hosts.
```

**Comment by fr0sty98** [comment]
I'll try to search more about cloud servers.
One more question..
Here it says standalone :
```
css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1:LOADING]: "WeaponPaints" (2.5a) by Nereziel & daffyy
    Skin, gloves, agents and knife selector, **standalone** and web-based
```
I didn't found any info how to use this plugin on server without web interface. Is this same plugin like it was earlier on server when you type !knife and then you choose from menu using numbers 1,2,3.. ?

**Comment by mrc4tt** [comment]
Something like that, yes. ^

You need to find a MySQL server provider that allows remote connection (outside of the current server IP)

**Comment by fr0sty98** [comment]
I mean something that will work game server based, without external database

**Comment by mrc4tt** [comment]
You can't use weaponpaints without a database.

**Comment by fr0sty98** [comment]
Alright, solved. Thanks for help :)

**Comment by mrc4tt** [comment]
> Alright, solved. Thanks for help :)

If solved, remember close the issue =D
