### ISSUE TITLE
Knives don't work

### ISSUE THREAD

**Issue by LukaLiuzzi** [Nereziel/cs2-WeaponPaints#286]
**I installed the plugin as explained in the readme and everything works for me except changing the knife (it always stays with the default) and changing the knife skin.**

**Comment by mrc4tt** [comment]
Make sure you edited core.json

Did you set **FollowCS2ServerGuidelines** to false?
Did you install the database, as it's requires

**Comment by LukaLiuzzi** [comment]
> Make sure you edited core.json
> 
> Did you set **FollowCS2ServerGuidelines** to false? Did you install the database, as it's requires

Yes i set FollowCS2ServerGuidelines to false and i already install the db

**Comment by NhNc0** [comment]
i have the same problem

**Comment by raszyniaczek** [comment]
After last updated knifes doesnt work on Windows server. Gloves and guns works fine. Any ideas?

**Comment by NhNc0** [comment]
> After last updated knifes doesnt work on Windows server. Gloves and guns works fine. Any ideas?

I have the problem months ago and i manage to make it work again, but this time simply stay on default knife. I dunno how to fix it. If i have a solution i message you kkkkk
