### ISSUE TITLE
Language file

### ISSUE THREAD

**Issue by ReDcTiOn** [Nereziel/cs2-WeaponPaints#29]
Please output all text into a separate file

**Comment by Nereziel** [comment]
Translations will be when cssharp will support them.

**Comment by daffyyyy** [comment]
Working on translations via config

**Comment by daffyyyy** [comment]
Done, PR #30

**Comment by Nereziel** [comment]
Merged, you can try.

**Comment by daffyyyy** [comment]
If you used the latest plugin, remember to remove the old config, cssharp unfortunately does not replace them (maybe yet).
