### ISSUE TITLE
website only shows skins not agents, gloves,music.

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#291]
Hi there @Nereziel and @daffyyyy 

I'm using latest release of this plugin with latest website files but after signing in with steam , I only see weapon skins . I don't see any agents , gloves or music to choose from .

What am I doing wrong? do I have to do anything in website files to make them show up?

Regards ,

**Comment by lostsoul6** [comment]
Any help will be appreciated @daffyyyy

**Comment by lowoa** [comment]
up

**Comment by lostsoul6** [comment]
@lowoa 

were you able to find out a solution? I can't fix it .

**Comment by NeiZeOne** [comment]
Any solution for this problem?

**Comment by lostsoul6** [comment]
@NeiZeOne absolutely nothing .

**Comment by lowoa** [comment]
usae other websites

**Comment by lostsoul6** [comment]
@lowoa what do you mean? what other websites?

**Comment by Nereziel** [comment]
Website is outdated, use 3rd party website for now.

**Comment by asdfxD** [comment]
still outdated? it looks like this, cant do anything on it.

![Unbenannt](https://github.com/user-attachments/assets/ad1cad56-46ba-4a5d-95d4-b5b9ec819484)
