### ISSUE TITLE
WP Not changing skins

### ISSUE THREAD

**Issue by BranDaddy283479** [Nereziel/cs2-WeaponPaints#292]
I have added WP to my server. I have connected my DB to this as well in the JSON file. For some reason, its not allowing me to change skins.. 
console gives me error of "Cannot Execute command 'slot', missing required FCVAR flag"
DB has been confirmed to be working and i am able to log into php admin etc. No other plugin has issues with it. 
Can someone please help me! 

Sending out tips to anyone who can help me get this running on my server :)

**Comment by No123567** [comment]
I am also having this problem hopefully they fix it soon
