### ISSUE TITLE
Can you support a more aesthetically pleasing in-game skin change menu?

### ISSUE THREAD

**Issue by 1370533448** [Nereziel/cs2-WeaponPaints#293]
Can you support interactive menu systems similar to:
https://github.com/NickFox007/MenuManagerCS2/tree/main
https://github.com/Interesting-exe/WASDMenuAPI
for in-game skin changes? A

**Comment by originalaidn** [comment]
added with stickers & keychains in 2.6a release

need 3 dependencies, those in readme
