### ISSUE TITLE
Access Denied for User (Website)

### ISSUE THREAD

**Issue by smpcheathunt** [Nereziel/cs2-WeaponPaints#295]
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) in /home/awmdplem/domains/cheathunt.x10.mx/public_html/class/database.php:8
Stack trace:
#0 /home/awmdplem/domains/cheathunt.x10.mx/public_html/class/database.php(8): PDO->__construct()
#1 /home/awmdplem/domains/cheathunt.x10.mx/public_html/index.php(7): DataBase->__construct()
#2 {main}

this is the log

**Comment by L1teD** [comment]
Check you database credentials as well as MySQL configuration

**Comment by smpcheathunt** [comment]
I'm pretty sure it's the same? Since it is a dedicated server I put the credentials host as localhost and username as root. I must be stupid.

**Comment by L1teD** [comment]
As i see you have no password for mysql set
This could be the issue (but I'm not sure, since i don't remember how pdo in php works)
Try to set a password for root and see if it works

**Comment by smpcheathunt** [comment]
I did, but it just changed  to (using password: YES)

**Comment by romerocox** [comment]
This issue is at the database level, needs to be correctly configured. It's the combinationa of username/password that is not matching. If necessary, create another user and set the correct credentials.
