### ISSUE TITLE
Plugin "Prefix" not replaced

### ISSUE THREAD

**Issue by LelieL91** [Nereziel/cs2-WeaponPaints#296]
Hi,

I correctly installed the plugin on the server, the database it's working as the website using latest Nginx, http3 and latest php 8.3.
The only "issue" I am having is the "Prefix" config variable, that even if set, it's totally ignored, in-game there is still the default value [WeaponPaints].

Thank your for your work

**Comment by jke-cs** [comment]
Yes true its getting ignored in the config, but you can adjust the prefix in the language file /plugins/WeaponPaints/lang/en.json to display what ever you want

**Comment by LelieL91** [comment]
> Yes true its getting ignored in the config, but you can adjust the prefix in the language file /plugins/WeaponPaints/lang/en.json to display what ever you want

Thank you for your reply. I just had a look at the lang file, and noticed that "wp_prefix" got [WeaponPaints] hardcoded there, so I tried like the other entries by replacing "WeaponPaints" with "{0}", but the variable returns {0} as a string, it doesn't expand the var
