### ISSUE TITLE
After update knifes doesnt work anymore

### ISSUE THREAD

**Issue by raszyniaczek** [Nereziel/cs2-WeaponPaints#306]
Hi, after new update knifes doesnt work. Previous build works all good. Now knifes dont work.

**Comment by fuzzyscn** [comment]
change json file in gamedata folder，use this sig for ChangeSubclass: 48 89 6C 24 ? 56 48 83 EC ? 48 8B EA 48 8B F1 E8 ? ? ? ? 84 C0 0F 84

**Comment by raszyniaczek** [comment]
> change json file in gamedata folder，use this sig for Windows ChangeSubclass: 48 89 6C 24 ? 56 48 83 EC ? 48 8B EA 48 8B F1 E8 ? ? ? ? 84 C0 0F 84

Doesnt work :(

**Comment by ZanderJi** [comment]
> change json file in gamedata folder，use this sig for Windows ChangeSubclass: 48 89 6C 24 ? 56 48 83 EC ? 48 8B EA 48 8B F1 E8 ? ? ? ? 84 C0 0F 84

It works! Thanks

**Comment by raszyniaczek** [comment]
> > change json file in gamedata folder，use this sig for Windows ChangeSubclass: 48 89 6C 24 ? 56 48 83 EC ? 48 8B EA 48 8B F1 E8 ? ? ? ? 84 C0 0F 84
> 
> It works! Thanks

For me doesnt work hmmm i dont know whats wrong

**Comment by ZanderJi** [comment]
> > > change json file in gamedata folder，use this sig for Windows ChangeSubclass: 48 89 6C 24 ? 56 48 83 EC ? 48 8B EA 48 8B F1 E8 ? ? ? ? 84 C0 0F 84
> > 
> > 
> > It works! Thanks
> 
> For me doesnt work hmmm i dont know whats wrong

i change gamedata.json under counterstrikesharp\gamedata folder, then i restart server and it works

**Comment by raszyniaczek** [comment]
Aaa okey, on CSS gamedata not in WeaponPaints gamedata

niedz., 6 paź 2024, 15:28 użytkownik ZanderJi ***@***.***>
napisał:

**Comment by raszyniaczek** [comment]
> > > > change json file in gamedata folder，use this sig for Windows ChangeSubclass: 48 89 6C 24 ? 56 48 83 EC ? 48 8B EA 48 8B F1 E8 ? ? ? ? 84 C0 0F 84
> > > 
> > > 
> > > It works! Thanks
> > 
> > 
> > For me doesnt work hmmm i dont know whats wrong
> 
> i change weaponpaints.json under counterstrikesharp\gamedata folder, then i restart server and it works

It works!!!!

**Comment by mrc4tt** [comment]
@raszyniaczek if it works, remember to close this issue. :-)
