### ISSUE TITLE
KitsuneMenu

### ISSUE THREAD

**Issue by gha241** [Nereziel/cs2-WeaponPaints#309]
Will you add KitsuneMenu to the plugin?

**Comment by gha241** [comment]
@Nereziel

**Comment by gha241** [comment]
that's what I mean
![IMG_20241013_081906](https://github.com/user-attachments/assets/0599d33b-3947-4c3f-ac75-d509cfe78b11)

**Comment by 1370533448** [comment]
No, it won't
