### ISSUE TITLE
 Unknown column Database

### ISSUE THREAD

**Issue by gha241** [Nereziel/cs2-WeaponPaints#328]
[WeaponPaints] An error occurred in GetKnifeFromDatabase: Unknown column 'weapon_team' in 'field list'
[WeaponPaints] An error occurred in GetGlovesFromDatabase: Unknown column 'weapon_team' in 'field list'
[WeaponPaints] An error occurred in GetMusicFromDatabase: Unknown column 'weapon_team' in 'field list'
[WeaponPaints] An error occurred in GetPinsFromDatabase: Unknown column 'weapon_team' in 'field list'

**Comment by gha241** [comment]
@originalaidn

**Comment by Oneycs** [comment]
Did you had WeaponPoints installed or is this fresh installation?

**Comment by gha241** [comment]
was installed

**Comment by Oneycs** [comment]
yeah, so you need to login to your database and delete the wp_ columns. Beacuse it doesnt have the new columns and doing that will add them. Watch out it will erase every selected skins on your server for everyone.

**Comment by originalaidn** [comment]
Please drop (delete) your wp_ tables (agents not needed). Others needed, because in the last releases, daffyy added team based items.
And not enough if creating new columns (weapon_team), need to add uniques. Thats why drop is easier.

But with drop, all selected item will be erased

**Comment by gha241** [comment]
thanks :)
