### ISSUE TITLE
Will the website be fixed?

### ISSUE THREAD

**Issue by AngelBePro** [Nereziel/cs2-WeaponPaints#333]
After the new team based update, the website doesn't really function. It works, until you try and change a skin, thats when you get a error 500. Sorry If no one else has this issue.

**Comment by AngelBePro** [comment]
> Same, updated to hopefully fix the knives not working, but now the site returns error 500 when you select the skin you want. :(

Everything works with the main plugin but you need to use the command.

**Comment by TPPH** [comment]
what build do you use, because my plugin doesnt work, even the !skins etc?
