### ISSUE TITLE
Is it possible to add charms to skins?

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#338]
Hi there @Nereziel and @daffyyyy 

Is it possible to add charms to skins? I remember I asked daffyy once for stickers and he said it's not technically possible . what about charms ? any way to add them ? thank you.

**Comment by Oneycs** [comment]
Charms were added but i dont think they completed it for it to work. You must wait until they add a command for that.

**Comment by lostsoul6** [comment]
@Oneycs I'm not using the latest version . In the version I'm using there is no signs of them but it's good to know that it's possible and it will be added in the future . thanks .

**Comment by Oneycs** [comment]
Its not in the latest version. They added the code but I dont know if they forgot to add the command or what.

**Comment by jke-cs** [comment]
its currently been worked on a website where you can apply stickers and charms, that would be the easiest way

**Comment by lostsoul6** [comment]
@jke-cs Which website is that? I currently have the one L1Ted developed

**Comment by daffyyyy** [comment]
U can apply manually in database, plugin support both stickers and keychains. Currently no time to add menu for both, but soon

**Comment by lostsoul6** [comment]
@daffyyyy thank you so much ! even stickers? wow . I will wait for the official release whenever you find the time .

**Comment by daffyyyy** [comment]
> @daffyyyy thank you so much ! even stickers? wow . I will wait for the official release whenever you find the time . 

Yep, plugin support keychains and stickers
