### ISSUE TITLE
Will the keychain be supported?

### ISSUE THREAD

**Issue by NoSetViolin** [Nereziel/cs2-WeaponPaints#346]
i saw the "keychain" words in sql files, will it be supported?

**Comment by L1teD** [comment]
Already supported

**Comment by NoSetViolin** [comment]
but how to use? i saw the comment in sql files, i modified it but it doesn't work

**Comment by L1teD** [comment]
Try this value for sticker on ak47 `7913;0;-0.11637188258286545;0.0033881932021466808;0;0;0

**Comment by NoSetViolin** [comment]
> Try this value for sticker on ak47 `7913;0;-0.11637188258286545;0.0033881932021466808;0;0;0`

thanks,i'll try it. and does keychain work?

**Comment by NoSetViolin** [comment]
i tried for ak47 like this `('76561199480946274',2,7,707,0.514,114,NULL,0,0,'7913;0;-0.11637188258286545;0.0033881932021466808;0;0;0','7913;0;-0.11637188258286545;0.0033881932021466808;0;0;0','0;0;0;0;0;0;0','0;0;0;0;0;0;0','0;0;0;0;0;0;0','0;0;0;0;0')`
and refresh weaponpaints, it nothing happens

**Comment by NoSetViolin** [comment]
i tried sticker for ak47 it works! but if i need other stickers, how can i know it's id?

**Comment by L1teD** [comment]
Keychain also works, use cs2inspects for now for x, y values while i developing my website

**Comment by NoSetViolin** [comment]
> Keychain also works, use cs2inspects for now for x, y values while i developing my website

bro thankyou very much, i had tried stickers and keychains, they works fine. 
and ur website is very easy to use. I am looking forward to your release of a version with replaceable stickers and keychains. I just changed the stickers and keychains of a weapon for my friend and I'm exhausted lol

**Comment by 3Pinky3** [comment]
I selected a keychain on the website, but it did not appear anywhere. I still do not understand what the sql files is and what cs2inspects is used for.  Can you help me? 
How it looks on the website [image](https://imgur.com/a/ZMuB9w8)*
