### ISSUE TITLE
Problem with latest version.

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#347]
Hello @daffyyyy 

I was using version 2.5a and updated to latest release . After updating , when I joined the server , the plugin was loaded but I had no skins on any weapons. The newest release didn't load any of my previously selected skins . It seems the new release can not use the data that is stored in the database . has the database format changed from version 2.5a to latest release?

**Comment by lostsoul6** [comment]
@daffyyyy I also ran the database query but still when entering the server , none of my skins are loaded from database .

![Uploading ran-query.PNG…]()

**Comment by lostsoul6** [comment]
@daffyyyy 

I see these in console . seems the database format is still not right for the latest version : 

![error-wp](https://github.com/user-attachments/assets/02c2f01b-4d1d-485b-bd4f-d0fa42a2f180)

**Comment by Oneycs** [comment]
Try adding these queries to the DB:

```
ALTER TABLE wp_player_skins
ADD COLUMN weapon_nametag VARCHAR(128) DEFAULT NULL,
ADD COLUMN weapon_stattrak tinyint(1) NOT NULL,
ADD COLUMN weapon_stattrak_count int(10) NOT NULL,
ADD COLUMN weapon_sticker_0 VARCHAR(128) DEFAULT '0;0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
ADD COLUMN weapon_sticker_1 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
ADD COLUMN weapon_sticker_2 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
ADD COLUMN weapon_sticker_3 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
ADD COLUMN weapon_sticker_4 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
ADD COLUMN weapon_keychain VARCHAR(128) DEFAULT '0;0;0;0;0' COMMENT 'id;x;y;z;seed';```

**Comment by lostsoul6** [comment]
@Oneycs Already did that . please see the second post.

**Comment by MSWS** [comment]
Looks like adding
```sql
ALTER TABLE wp_player_skins
    ADD COLUMN weapon_team tinyint(1) NOT NULL;
```

worked for me. If you haven't run the first query, then you probably want to do

```sql
ALTER TABLE wp_player_skins
    ADD COLUMN weapon_nametag VARCHAR(128) DEFAULT NULL,
    ADD COLUMN weapon_stattrak tinyint(1) NOT NULL,
    ADD COLUMN weapon_stattrak_count int(10) NOT NULL,
    ADD COLUMN weapon_sticker_0 VARCHAR(128) DEFAULT '0;0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
    ADD COLUMN weapon_sticker_1 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
    ADD COLUMN weapon_sticker_2 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
    ADD COLUMN weapon_sticker_3 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
    ADD COLUMN weapon_sticker_4 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
    ADD COLUMN weapon_keychain VARCHAR(128) DEFAULT '0;0;0;0;0' COMMENT 'id;x;y;z;seed',
    ADD COLUMN weapon_team tinyint(1) NOT NULL;
```

**Comment by Oneycs** [comment]
ALTER TABLE wp_player_skins
    ADD COLUMN weapon_team tinyint(1) NOT NULL;

> Looks like adding
> 
> ```sql
> ALTER TABLE wp_player_skins
>     ADD COLUMN weapon_team tinyint(1) NOT NULL;
> ```
> 
> worked for me. If you haven't run the first query, then you probably want to do
> 
> ```sql
> ALTER TABLE wp_player_skins
>     ADD COLUMN weapon_nametag VARCHAR(128) DEFAULT NULL,
>     ADD COLUMN weapon_stattrak tinyint(1) NOT NULL,
>     ADD COLUMN weapon_stattrak_count int(10) NOT NULL,
>     ADD COLUMN weapon_sticker_0 VARCHAR(128) DEFAULT '0;0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
>     ADD COLUMN weapon_sticker_1 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
>     ADD COLUMN weapon_sticker_2 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
>     ADD COLUMN weapon_sticker_3 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
>     ADD COLUMN weapon_sticker_4 VARCHAR(128) DEFAULT '0;0;0;0;0;0' COMMENT 'id;schema;x;y;wear;scale;rotation',
>     ADD COLUMN weapon_keychain VARCHAR(128) DEFAULT '0;0;0;0;0' COMMENT 'id;x;y;z;seed',
>     ADD COLUMN weapon_team tinyint(1) NOT NULL;
> ```

Little update. As @MSWS said, you need to add wp_player_skins but made a little mistake in the code:
```
ALTER TABLE wp_player_skins
    ADD COLUMN weapon_team int(1) NOT NULL;
```

**Comment by lostsoul6** [comment]
@Oneycs thank you I will try it . Btw , is there any discord server for wp plugin? Daffyy told me these issues have been discussed there but I can't seem to find the discord server.

**Comment by Oneycs** [comment]
> @Oneycs thank you I will try it . Btw , is there any discord server for wp plugin? Daffyy told me these issues have been discussed there but I can't seem to find the discord server.

https://github.com/Nereziel/cs2-WeaponPaints?tab=readme-ov-file#created-discord-server-where-you-can-discuss-about-plugin
