### ISSUE TITLE
error with database.php

### ISSUE THREAD

**Issue by JeoGit** [Nereziel/cs2-WeaponPaints#350]
![image](https://github.com/user-attachments/assets/c9393abe-c837-4924-bb88-fc69680e4144)
when trying to update and change skins I get this error, as well as the skins do not work in game

**Comment by Oneycs** [comment]
Add this column to your database:

```sql
ALTER TABLE wp_player_skins
    ADD COLUMN weapon_team int(1) NOT NULL;
```
