### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by itsbantist** [Nereziel/cs2-WeaponPaints#351]
04:44:52 [INFO] (cssharp:PluginContext) Finished loading plugin WeaponPaints
04:44:52 [EROR] (plugin:WeaponPaints) Error while loading required plugins
04:44:52 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
System.Collections.Generic.KeyNotFoundException: The given key 'menu:nfcore' was not present in the dictionary.

**Comment by daffyyyy** [comment]
okay, read readme first xD
