### ISSUE TITLE
Skins arent saving

### ISSUE THREAD

**Issue by gatusocs** [Nereziel/cs2-WeaponPaints#354]
I don't know why but in my server, the knife and gloves aren't saving, instead the agent and coin are. Any idea?

**Comment by Oneycs** [comment]
Does the console give any errors when you equip knives etc.?

**Comment by gatusocs** [comment]
actually yes. 
**Nov 12 20:39:27:  [All Chat][gatuso.- (341379896)]: !knife
Nov 12 20:39:27:  L 11/12/2024 - 20:39:27: "gatuso.-<2><[U:1:341379896]><TERRORIST>" say "!knife"
Nov 12 20:39:28:  [WeaponPaints] Error syncing knife to database: Unknown column 'weapon_team' in 'field list'**

**Comment by gatusocs** [comment]
There are errors when entering the server.
Nov 12 20:42:49:  [WeaponPaints] An error occurred in GetKnifeFromDatabase: Unknown column 'weapon_team' in 'field list'
Nov 12 20:42:49:  [WeaponPaints] An error occurred in GetGlovesFromDatabase: Unknown column 'weapon_team' in 'field list'
Nov 12 20:42:49:  [WeaponPaints] An error occurred in GetMusicFromDatabase: Unknown column 'weapon_team' in 'field list'
Nov 12 20:42:49:  [WeaponPaints] An error occurred in GetWeaponPaintsFromDatabase: Unknown column 'weapon_team' in 'order clause'

**Comment by gatusocs** [comment]
Sorry, Where is "field list"? Where I should put that?

**Comment by Oneycs** [comment]
Field list is in your Database. In your config you have set a database. You have to add the columns there.

**Comment by gatusocs** [comment]
I already did it but the problem persists
**Nov 14 00:52:32:  L 11/14/2024 - 00:52:32: "gatuso.-<2><[U:1:341379896]><TERRORIST>" say "!wp"
Nov 14 00:52:32:  [WeaponPaints] An error occurred in GetKnifeFromDatabase: Unknown column 'weapon_team' in 'field list'
Nov 14 00:52:32:  [WeaponPaints] An error occurred in GetGlovesFromDatabase: Unknown column 'weapon_team' in 'field list'
Nov 14 00:52:32:  [WeaponPaints] An error occurred in GetMusicFromDatabase: Unknown column 'weapon_team' in 'field list'
Nov 14 00:52:32:  [WeaponPaints] An error occurred in GetWeaponPaintsFromDatabase: Unknown column 'weapon_team' in 'order clause'
Nov 14 00:52:35:  [Allies Chat][gatuso.- (341379896)]: !knife
Nov 14 00:52:35:  L 11/14/2024 - 00:52:35: "gatuso.-<2><[U:1:341379896]><TERRORIST>" say_team "!knife"
Nov 14 00:52:36:  [WeaponPaints] Error syncing knife to database: Unknown column 'weapon_team' in 'field list'**

**Comment by gatusocs** [comment]
I solved this by modifying and adding columns to the database, both for knives, gloves and music, these are the queries that worked for me:

ALTER TABLE wp_player_knife 
MODIFY COLUMN weapon_team INT NULL;
UPDATE wp_player_knife SET weapon_team = 0 WHERE weapon_team IS NULL;

ALTER TABLE wp_player_gloves
ADD COLUMN weapon_team INT(10) NOT NULL DEFAULT 0;

ALTER TABLE wp_player_music
ADD COLUMN weapon_team INT(10) NOT NULL DEFAULT 0;
