### ISSUE TITLE
The m4a1-s weapon does not appear

### ISSUE THREAD

**Issue by babyvancho** [Nereziel/cs2-WeaponPaints#362]
The m4a1-s weapon does not appear in the menu to select skins.

**Comment by mrc4tt** [comment]
You need to provide logs from the gameserver's console.

Check if there are any "errors".

**Comment by babyvancho** [comment]
Could you tell me how I can get the logs to see them?

**Comment by mrc4tt** [comment]
Could you make sure you have installed the required correctly?

https://github.com/NickFox007/PlayerSettingsCS2
https://github.com/NickFox007/AnyBaseLibCS2
https://github.com/NickFox007/MenuManagerCS2

Edit `addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json` include database credentials.
In `addons/counterstrikesharp/configs/core.json` set **FollowCS2ServerGuidelines** to **false**

**Comment by babyvancho** [comment]
Yes, everything is set up correctly and when the plugin loads, no errors appear. In the CSS-BANS skin selection menu, all weapons appear except for this one.

**Comment by daffyyyy** [comment]
So, its not wp problem but css-bans.
