### ISSUE TITLE
[BUG] knife disappearing

### ISSUE THREAD

**Issue by himenekocn** [Nereziel/cs2-WeaponPaints#38]
when change knife form default to other , it will be disappearing.
this happen on windows server

**Comment by himenekocn** [comment]
And the !kill command will crash the server

**Comment by daffyyyy** [comment]
> And the !kill command will crash the server

cssharp version?

**Comment by 1370533448** [comment]
Yes, I've also noticed that using the 'kill' command causes a crash. The server version is up-to-date as of today. The operating system is Windows. After setting the knife on the web, there are no ordinary weapons in the game.

**Comment by daffyyyy** [comment]
> Yes, I've also noticed that using the 'kill' command causes a crash. The server version is up-to-date as of today. The operating system is Windows. After setting the knife on the web, there are no ordinary weapons in the game.

Latest game update causing server crashing when player try suicide, u can disable kill command in config and wait for cssharp update. about knife, try reconnect or !wp command

**Comment by himenekocn** [comment]
> > And the !kill command will crash the server
> 
> cssharp version & plugin version/release?

Cssharp 53 
Plugin Build 46

**Comment by himenekocn** [comment]
> > Yes, I've also noticed that using the 'kill' command causes a crash. The server version is up-to-date as of today. The operating system is Windows. After setting the knife on the web, there are no ordinary weapons in the game.
> 
> Latest game update causing server crashing when player try suicide, u can disable kill command in config and wait for cssharp update. about knife, try reconnect or !wp command

Reconnect or use !wp doesn't work, knife still disappearing.

**Comment by daffyyyy** [comment]
> On windows server i couldnt get knives working too, maybe wrong gamedata for func givenameditem.

then cssharp issue, not plugin issue :D

**Comment by himenekocn** [comment]
@Nereziel @daffyyyy I think is not givenameditem wrong, cause [cs2_weapons_skin](https://github.com/yuzhouUvU/cs2_weapons_skin/tree/main) can give the knives and it use givenameditem.

**Comment by daffyyyy** [comment]
[cs2_weapons_skin](https://github.com/yuzhouUvU/cs2_weapons_skin/tree/main) is in c++ and metamod plugin

**Comment by himenekocn** [comment]
> [cs2_weapons_skin](https://github.com/yuzhouUvU/cs2_weapons_skin/tree/main) is in c++ and metamod plugin

I mean, if Givenameditem doesn't work on windows, can we do it in a different way by following the cs2_weapons_skin way of working?

**Comment by himenekocn** [comment]
sprintf(buf,"i_subclass_change %d %d",knife_idx->second,index);
this is in cs2_weapons_skin 
it change knife skin on default knife

**Comment by himenekocn** [comment]
i see it need the FnSubClassChange = (SubClassChange_t)FindSignature("server.dll", "\x40\x55\x41\x57\x48\x83\xEC\x78\x83\xBA\x38\x04");
css not support...

**Comment by daffyyyy** [comment]
> when change knife form default to other , it will be disappearing. this happen on windows server

disappering? so you have some other plugins that are not compatible if it disappears for you

**Comment by himenekocn** [comment]
> > when change knife form default to other , it will be disappearing. this happen on windows server
> 
> disappering? so you have some other plugins that are not compatible if it disappears for you

Specifically, no knife in the slot, no other plugins to affect

**Comment by himenekocn** [comment]
> On windows server i couldnt get knives working too, maybe wrong gamedata for func givenameditem.

now i am sure the sig is true
![QQ截图20231118215325](https://github.com/Nereziel/cs2-WeaponPaints/assets/9393126/350c6a99-b379-4afd-a1f0-9f98e5406b6d)

**Comment by himenekocn** [comment]
@daffyyyy new version still no knife in the slot.

**Comment by himenekocn** [comment]
i think it must be change SubClass on windows
cs2_weapons_skin is use subclass change weapon_knife to other knives

**Comment by himenekocn** [comment]
[CounterStrikeSharp](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e)/[managed](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e/managed)/[CounterStrikeSharp.API](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e/managed/CounterStrikeSharp.API)/[Core](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e/managed/CounterStrikeSharp.API/Core)
/API.cs have FindSignature can add a new func for SubClassChange

**Comment by himenekocn** [comment]
CreateVirtualFunctionBySignature

**Comment by wavypzuto** [comment]
same issue : (, any hope to fix this guys?

**Comment by Nereziel** [comment]
> i think it must be change SubClass on windows cs2_weapons_skin is use subclass change weapon_knife to other knives

sadly, i dont know how to reinterpret that func in c#

**Comment by himenekocn** [comment]
> > i think it must be change SubClass on windows cs2_weapons_skin is use subclass change weapon_knife to other knives
> 
> sadly, i dont know how to reinterpret that func in c#

use CreateVirtualFunctionBySignature func
It is in [CounterStrikeSharp](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e)/[managed](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e/managed)/[CounterStrikeSharp.API](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e/managed/CounterStrikeSharp.API)/[Core](https://github.com/roflmuffin/CounterStrikeSharp/tree/04e7ed682acb8827382103a4c991ea6ce25faf3e/managed/CounterStrikeSharp.API/Core)
/API.cs

**Comment by himenekocn** [comment]
> > i think it must be change SubClass on windows cs2_weapons_skin is use subclass change weapon_knife to other knives
> 
> sadly, i dont know how to reinterpret that func in c#

public static IntPtr CreateVirtualFunctionBySignature(IntPtr pointer, string binaryname, string signature, int numarguments, int returntype, object[] arguments)
