### ISSUE TITLE
[BUG] Knife disappearing on retake

### ISSUE THREAD

**Issue by brutalcinikola** [Nereziel/cs2-WeaponPaints#45]
Knife loads, but after you choose your weapon card it switches to default knife, if I switch to casual mode it works fine so its a Retake gamemode bug. Is there any way to fix this?

**Comment by daffyyyy** [comment]
Try latest version, can't reproduce issue
https://i.imgur.com/1ATeW9v.mp4

**Comment by audiomaster99** [comment]
> Try latest version, can't reproduce issue https://i.imgur.com/1ATeW9v.mp4

https://imgur.com/5NkNPzj

**Comment by daffyyyy** [comment]
Server on windows or linux?

**Comment by audiomaster99** [comment]
Linux, css v56, lates build of weapon paints

**Comment by daffyyyy** [comment]
Can u add me on discord? daffyy or join https://discord.gg/mwEQppJ5AT

**Comment by audiomaster99** [comment]
Build 60, fixes knife problem on retake
