### ISSUE TITLE
[BUG] Website option to Select Skin for the knife and weapons

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#49]
When we select a opção `Select Skin` for the knife or weapons, the page reloads and turns white.

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/32937653/de835530-1f00-4ee3-9c11-252d76661c05)

In my tests it occurred on all knife and weapon skins.

**Comment by daffyyyy** [comment]
Try latest version (index.php)

**Comment by crashzk** [comment]
> Try latest version (index.php)

![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/32937653/3b4af048-bac7-4911-a4ac-c6d4dda5e17d)

**Comment by daffyyyy** [comment]
PHP version?

**Comment by crashzk** [comment]
> PHP version?
> 
> Add
> 
> ```
> ini_set('display_errors', 1);
> ini_set('display_startup_errors', 1);
> error_reporting(E_ALL);
> ```
> 
> To index.php top, after first <?php and whats error shows?

PHP 8.2

```
Warning: Undefined array key 1 in /home/zkservid/public_html/cs2/index.php on line 29

Warning: Undefined array key "Select skin" in /home/zkservid/public_html/cs2/index.php on line 29

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /home/zkservid/public_html/cs2/index.php:29 Stack trace: #0 {main} thrown in /home/zkservid/public_html/cs2/index.php on line 29
```

**Comment by daffyyyy** [comment]
You must have edited something wrong in that case

**Comment by daffyyyy** [comment]
Downlaod entire website, and upload again

**Comment by crashzk** [comment]
> You must have edited something wrong in that case

Strange, I didn't edit it, I just downloaded the latest version and sent it to the server and web.

I only configured the database and the Steam API Key.

**Comment by daffyyyy** [comment]
My mistake, I forgot that you can select "Select skin" :D It will be corrected in the latest version

**Comment by daffyyyy** [comment]
@crashzk  check now

**Comment by crashzk** [comment]
Fix
