### ISSUE TITLE
Doubt with Kill Command

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#52]
Any ways to disable the message from this command and the command itself?

Would you like to disable this feature, or would this generate a bug when the player chooses the knife skin?

**Comment by daffyyyy** [comment]
Use latest release and remove old config.  Then u can disable kill command

**Comment by crashzk** [comment]
> Use latest release and remove old config. Then u can disable kill command

Ok, just a note, I downloaded the latest version and sent it to a clean server, the configuration generated and the command was there, would I just remove it in this case? Or was he not supposed to show up?

**Comment by daffyyyy** [comment]
> > Use latest release and remove old config. Then u can disable kill command
> 
> Ok, just a note, I downloaded the latest version and sent it to a clean server, the configuration generated and the command was there, would I just remove it in this case? Or was he not supposed to show up?

`"CommandKillEnabled": true,`
Change to false and try
