### ISSUE TITLE
[REQ] Support Music Kit & Coins

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#53]
Support for official valve music kits as well as all coins.

I believe we can implement this feature and thus take the "focus" away from just skins and knives, leaving a complete inventory plugin for CS2.

**Comment by kolibrzyk** [comment]
U can get banned by Valve so idk if its good idea to add it

**Comment by Nereziel** [comment]
> U can get banned by Valve so idk if its good idea to add it

You can be banned for changing skins too so not a big deal.

**Comment by lostsoul6** [comment]
> > U can get banned by Valve so idk if its good idea to add it
> 
> And where did you get this information from? Valve bans the token from its server and has not done that for years, and there is already a way to get around this.
> 
> Following your reasoning then, not even WS and Knife should exist then, which also generates banishment!

@crashzk Hi there , can you please explain more about what you mean when you said there are ways to get around this? I'm using WeaponPaints and I'm worried that valve would ban the server . If there is a way to bypass their checks , I would be grateful if you can mention it . Thanks .

**Comment by originalaidn** [comment]
music kits was supported, in 2.7a pins added
