### ISSUE TITLE
Doubt with web interface

### ISSUE THREAD

**Issue by crashzk** [Nereziel/cs2-WeaponPaints#57]
Every time we choose a skin the page reloads, would it be possible to remove this feature? Or would it be necessary?

It would be possible to let only the skin update on the server and in the web interface and not reload the page itself.

**Comment by daffyyyy** [comment]
We are currently focusing on something else, maybe in some time

**Comment by Nereziel** [comment]
The refresh is needed because we update data in POST form right now.
