### ISSUE TITLE
Skins not editable in database

### ISSUE THREAD

**Issue by asdfxD** [Nereziel/cs2-WeaponPaints#65]
skins are not editable in phpmyadmin database. i try to add indices in table so i can edit the skins (seed for example), but web page stops working than.

**Comment by daffyyyy** [comment]
If you edit something yourself, what does it have to do with our work?

**Comment by asdfxD** [comment]
no, the skins are not editable with the standard plugin. thats what i mean.

**Comment by daffyyyy** [comment]
> Author

You edit skins on the website, not the database xD

**Comment by asdfxD** [comment]
....

in web you can't edit seed, but in phpmyadmin it works.

**Comment by daffyyyy** [comment]
> ....
> 
> in web you can't edit seed, but in phpmyadmin it works.

So learn basic mysql queries before opening an issue?

**Comment by Nereziel** [comment]
We have not implemented changing seed, wear etc. in website.

**Comment by exababy** [comment]
> skins are not editable in phpmyadmin database. i try to add indices in table so i can edit the skins (seed for example), but web page stops working than.

please delete computer
