### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Truyn** [Nereziel/cs2-WeaponPaints#70]
https://github.com/Nereziel/cs2-WeaponPaints/issues/10
I don't understand what's wrong, php 8.2
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/53527324/2f8c258c-7b2d-47ac-8e4b-38e14c7fffc3)

**Comment by asdfxD** [comment]
Same on php 8.1, back to old and not recommended 7.4....

**Comment by Nereziel** [comment]
try add **ini_set('display_errors', 1);** to index.php

![obrazek](https://github.com/Nereziel/cs2-WeaponPaints/assets/8618825/dc4510f9-9274-41d0-9eb0-9fbc9c8cf3df)

**Comment by Truyn** [comment]
Thx, i idiot, not access databases.
