### ISSUE TITLE
Http 500 error logs 

### ISSUE THREAD

**Issue by VatanLegend** [Nereziel/cs2-WeaponPaints#81]
select("SELECT `weapon_defindex`, `weapon_paint_id` FROM `wp_player_skins` WHERE `wp_player_skins`.`steamid` = :steamid", ["steamid" => $steamid]); $selectedSkins = UtilsClass::getSelectedSkins($querySelected); $selectedKnife = $db->select("SELECT * FROM `wp_player_knife` WHERE `wp_player_knife`.`steamid` = :steamid", ["steamid" => $steamid])[0]; $knifes = UtilsClass::getKnifeTypes(); if (isset($_POST['forma'])) { $ex = explode("-", $_POST['forma']); if ($ex[0] == "knife") { $db->query("INSERT INTO `wp_player_knife` (`steamid`, `knife`) VALUES(:steamid, :knife) ON DUPLICATE KEY UPDATE `knife` = :knife", ["steamid" => $steamid, "knife" => $knifes[$ex[1]]['weapon_name']]); } else { if (!is_int($ex[1])) header("Location: index.php"); if (array_key_exists($ex[1], $skins[$ex[0]])) { if (array_key_exists($ex[0], $selectedSkins)) { $db->query("UPDATE wp_player_skins SET weapon_paint_id = :weapon_paint_id WHERE steamid = :steamid AND weapon_defindex = :weapon_defindex", ["steamid" => $steamid, "weapon_defindex" => $ex[0], "weapon_paint_id" => $ex[1]]); } else { $db->query("INSERT INTO wp_player_skins (`steamid`, `weapon_defindex`, `weapon_paint_id`) VALUES (:steamid, :weapon_defindex, :weapon_paint_id)", ["steamid" => $steamid, "weapon_defindex" => $ex[0], "weapon_paint_id" => $ex[1]]); } } } header("Location: index.php"); } } ?>
To choose weapon paints loadout, you need to

**Comment by 925916995** [comment]
After entering the server, setting up a knife, refreshing it and it can be used now

**Comment by VatanLegend** [comment]
Entering the server ,setting up knife and refreshing but site not working

**Comment by Nereziel** [comment]
try new version

**Comment by Nereziel** [comment]
No feedback
