### ISSUE TITLE
need help Instructions not understandable for me

### ISSUE THREAD

**Issue by jinnsTaRR** [Nereziel/cs2-WeaponPaints#84]
I don't fully understand it, I have GlobalShare = true so I don't need the web installer or am I wrong? How do you choose skins now?
and if I need the web installer, what do I have to do with the website folder?  "Fill in database credentials and api key in class/config.php;" but what do I do with this folder?

**Comment by audiomaster99** [comment]
![image](https://github.com/Nereziel/cs2-WeaponPaints/assets/116572799/30bf5221-96df-4075-bc80-c1ce7c641e45)

**Comment by jinnsTaRR** [comment]
okay and now on weaponpaints.fun i must choose my server, but when i type !wp the skins dont refresh.
