### ISSUE TITLE
Possibile to Save Skins for Player?

### ISSUE THREAD

**Issue by jinnixyz** [Nereziel/cs2-WeaponPaints#86]
Is it possible to set up so that when a player comes to the server again, the set skins are loaded automatically or remain saved?

**Comment by rabi07** [comment]
Lol, I think you dont even try the plugin yet or read the readme section

**Comment by jinnsTaRR** [comment]
I have installed it. What you mean? Am 04.12.23 um 02:26 schrieb Rabi
                
            
            
                
                    Von: "Rabi" ***@***.***>Datum: 4. Dezember 2023An: "Nereziel/cs2-WeaponPaints" ***@***.***>Cc: "jinnsTaRR" ***@***.***>,"Author" ***@***.***>Betreff: Re: [Nereziel/cs2-WeaponPaints] Possibile to Save Skins for Player? (Issue #86)
                
                
Lol, I think you dont even try the plugin yet or read the readme section

**Comment by jinnsTaRR** [comment]
> Lol, I think you dont even try the plugin yet or read the readme section

i have installed the plugin and read the readme section. what do you want to tell me?
When players quit or the map changed all the skins are resetet.

**Comment by asdfxD** [comment]
why does the ak or any other gun always reloading when you buy them? also i know this is the skin replacement, but why it doesn't work as in csgo?

**Comment by Nereziel** [comment]
@jinnsTaRR is the problem gone with newest version?

**Comment by jinnsTaRR** [comment]
> @jinnsTaRR is the problem gone with newest version?

It's a bit strange, some skins are saved but some aren't. with !knife it doesn't load the selected knife either. Do you already know anything about it?

**Comment by Nereziel** [comment]
> > @jinnsTaRR is the problem gone with newest version?
> 
> It's a bit strange, some skins are saved but some aren't. with !knife it doesn't load the selected knife either. Do you already know anything about it?

I can’t reproduce your problem. Skins are saved and also loaded on reconnect.

**Comment by asdfxD** [comment]
> why does the ak or any other gun always reloading when you buy them? also i know this is the skin replacement, but why it doesn't work as in csgo?

does this ever gets fixed? i buy 4 nades and my fake ak skin or whatever gun i use reloads 4 times!! Franugs ws plugin does not have this issue.
