### ISSUE TITLE
Problem with pulling skins

### ISSUE THREAD

**Issue by EmiNarkotik** [Nereziel/cs2-WeaponPaints#92]
hello
my server is have a problem. ı not understand.
default knife change working. Skin change don't working.

https://prnt.sc/zMN5wckxcAJV    Knife
https://prnt.sc/8Y6RJyV89NZf   all weapons have same problem

**Comment by EmiNarkotik** [comment]
> hello my server is have a problem. ı not understand. default knife change working. Skin change don't working.
> 
> https://prnt.sc/zMN5wckxcAJV Knife https://prnt.sc/8Y6RJyV89NZf all weapons have same problem

Ok. Solved. :)
Thanks.

**Comment by FALL1N1** [comment]
@EmiNarkotik mind if you share information about the issue, please? How did you resolved it as I am experiencing the same issue.
